// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_receipt_scanner_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ScanSource(val raw: Int) {
  CAMERA(0),
  GALLERY(1);

  companion object {
    fun ofRaw(raw: Int): ScanSource? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ImageOrigin(val raw: Int) {
  CAMERA(0),
  SCREENSHOT(1),
  DOWNLOAD(2),
  UNKNOWN(3);

  companion object {
    fun ofRaw(raw: Int): ImageOrigin? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ScanStatus(val raw: Int) {
  SUCCESS(0),
  CANCELLED(1),
  REJECTED(2);

  companion object {
    fun ofRaw(raw: Int): ScanStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrFloorMessage (
  val minTextLength: Long? = null,
  val minLines: Long? = null,
  val minConfidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrFloorMessage {
      val minTextLength = pigeonVar_list[0] as Long?
      val minLines = pigeonVar_list[1] as Long?
      val minConfidence = pigeonVar_list[2] as Double?
      return OcrFloorMessage(minTextLength, minLines, minConfidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      minTextLength,
      minLines,
      minConfidence,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanOptions (
  val source: ScanSource? = null,
  val maxPages: Long? = null,
  val quality: Double? = null,
  val includeExif: Boolean? = null,
  val includeGpsExif: Boolean? = null,
  val ocr: Boolean? = null,
  val cropAutoConfirm: Boolean? = null,
  val autoRotate: Boolean? = null,
  val includeRawExif: Boolean? = null,
  val minimumTextHeight: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanOptions {
      val source = pigeonVar_list[0] as ScanSource?
      val maxPages = pigeonVar_list[1] as Long?
      val quality = pigeonVar_list[2] as Double?
      val includeExif = pigeonVar_list[3] as Boolean?
      val includeGpsExif = pigeonVar_list[4] as Boolean?
      val ocr = pigeonVar_list[5] as Boolean?
      val cropAutoConfirm = pigeonVar_list[6] as Boolean?
      val autoRotate = pigeonVar_list[7] as Boolean?
      val includeRawExif = pigeonVar_list[8] as Boolean?
      val minimumTextHeight = pigeonVar_list[9] as Double?
      return ScanOptions(source, maxPages, quality, includeExif, includeGpsExif, ocr, cropAutoConfirm, autoRotate, includeRawExif, minimumTextHeight)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      source,
      maxPages,
      quality,
      includeExif,
      includeGpsExif,
      ocr,
      cropAutoConfirm,
      autoRotate,
      includeRawExif,
      minimumTextHeight,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GpsData (
  val latitude: Double? = null,
  val longitude: Double? = null,
  val altitude: Double? = null,
  val timestamp: String? = null,
  val speed: Double? = null,
  val heading: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GpsData {
      val latitude = pigeonVar_list[0] as Double?
      val longitude = pigeonVar_list[1] as Double?
      val altitude = pigeonVar_list[2] as Double?
      val timestamp = pigeonVar_list[3] as String?
      val speed = pigeonVar_list[4] as Double?
      val heading = pigeonVar_list[5] as Double?
      return GpsData(latitude, longitude, altitude, timestamp, speed, heading)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      latitude,
      longitude,
      altitude,
      timestamp,
      speed,
      heading,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptExif (
  val orientation: Long? = null,
  val colorSpace: Long? = null,
  val lightSource: Long? = null,
  val exifVersion: String? = null,
  val make: String? = null,
  val model: String? = null,
  val software: String? = null,
  val dateTime: String? = null,
  val dateTimeOriginal: String? = null,
  val dateTimeDigitized: String? = null,
  val exposureTime: Double? = null,
  val fNumber: Double? = null,
  val iso: Double? = null,
  val focalLength: Double? = null,
  val flash: Long? = null,
  val whiteBalance: Long? = null,
  val exposureMode: Long? = null,
  val exposureProgram: Long? = null,
  val meteringMode: Long? = null,
  val gps: GpsData? = null,
  val raw: Map<String, Any?>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReceiptExif {
      val orientation = pigeonVar_list[0] as Long?
      val colorSpace = pigeonVar_list[1] as Long?
      val lightSource = pigeonVar_list[2] as Long?
      val exifVersion = pigeonVar_list[3] as String?
      val make = pigeonVar_list[4] as String?
      val model = pigeonVar_list[5] as String?
      val software = pigeonVar_list[6] as String?
      val dateTime = pigeonVar_list[7] as String?
      val dateTimeOriginal = pigeonVar_list[8] as String?
      val dateTimeDigitized = pigeonVar_list[9] as String?
      val exposureTime = pigeonVar_list[10] as Double?
      val fNumber = pigeonVar_list[11] as Double?
      val iso = pigeonVar_list[12] as Double?
      val focalLength = pigeonVar_list[13] as Double?
      val flash = pigeonVar_list[14] as Long?
      val whiteBalance = pigeonVar_list[15] as Long?
      val exposureMode = pigeonVar_list[16] as Long?
      val exposureProgram = pigeonVar_list[17] as Long?
      val meteringMode = pigeonVar_list[18] as Long?
      val gps = pigeonVar_list[19] as GpsData?
      val raw = pigeonVar_list[20] as Map<String, Any?>?
      return ReceiptExif(orientation, colorSpace, lightSource, exifVersion, make, model, software, dateTime, dateTimeOriginal, dateTimeDigitized, exposureTime, fNumber, iso, focalLength, flash, whiteBalance, exposureMode, exposureProgram, meteringMode, gps, raw)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      orientation,
      colorSpace,
      lightSource,
      exifVersion,
      make,
      model,
      software,
      dateTime,
      dateTimeOriginal,
      dateTimeDigitized,
      exposureTime,
      fNumber,
      iso,
      focalLength,
      flash,
      whiteBalance,
      exposureMode,
      exposureProgram,
      meteringMode,
      gps,
      raw,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrQuality (
  val textLength: Long? = null,
  val lineCount: Long? = null,
  val confidence: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): OcrQuality {
      val textLength = pigeonVar_list[0] as Long?
      val lineCount = pigeonVar_list[1] as Long?
      val confidence = pigeonVar_list[2] as Double?
      return OcrQuality(textLength, lineCount, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      textLength,
      lineCount,
      confidence,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptImage (
  val uri: String,
  val width: Long,
  val height: Long,
  val fileName: String,
  val mimeType: String,
  val fileSize: Long,
  val imageOrigin: ImageOrigin,
  val ocrText: String? = null,
  val ocrQuality: OcrQuality? = null,
  val exif: ReceiptExif? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ReceiptImage {
      val uri = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val fileName = pigeonVar_list[3] as String
      val mimeType = pigeonVar_list[4] as String
      val fileSize = pigeonVar_list[5] as Long
      val imageOrigin = pigeonVar_list[6] as ImageOrigin
      val ocrText = pigeonVar_list[7] as String?
      val ocrQuality = pigeonVar_list[8] as OcrQuality?
      val exif = pigeonVar_list[9] as ReceiptExif?
      return ReceiptImage(uri, width, height, fileName, mimeType, fileSize, imageOrigin, ocrText, ocrQuality, exif)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      uri,
      width,
      height,
      fileName,
      mimeType,
      fileSize,
      imageOrigin,
      ocrText,
      ocrQuality,
      exif,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResult (
  val status: ScanStatus,
  val images: List<ReceiptImage>,
  val rejectedImages: List<ReceiptImage>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ScanResult {
      val status = pigeonVar_list[0] as ScanStatus
      val images = pigeonVar_list[1] as List<ReceiptImage>
      val rejectedImages = pigeonVar_list[2] as List<ReceiptImage>
      return ScanResult(status, images, rejectedImages)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      status,
      images,
      rejectedImages,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanSource.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ImageOrigin.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ScanStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrFloorMessage.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanOptions.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GpsData.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReceiptExif.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          OcrQuality.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ReceiptImage.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ScanResult.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ScanSource -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ImageOrigin -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is ScanStatus -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is OcrFloorMessage -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is ScanOptions -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is GpsData -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ReceiptExif -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is OcrQuality -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is ReceiptImage -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ScanResult -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ReceiptScannerApi {
  fun scan(options: ScanOptions, callback: (Result<ScanResult>) -> Unit)

  companion object {
    /** The codec used by ReceiptScannerApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `ReceiptScannerApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: ReceiptScannerApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_receipt_scanner_platform_interface.ReceiptScannerApi.scan$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val optionsArg = args[0] as ScanOptions
            api.scan(optionsArg) { result: Result<ScanResult> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
