name: flutter_receipt_scanner_ios
description: iOS implementation of flutter_receipt_scanner.
version: 0.1.0
publish_to: none
resolution: workspace
environment:
  sdk: ">=3.12.0 <4.0.0"
  flutter: ">=3.44.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_receipt_scanner_platform_interface: ^0.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
flutter:
  plugin:
    implements: flutter_receipt_scanner
    platforms:
      ios:
        dartPluginClass: FlutterReceiptScannerIos
        pluginClass: FlutterReceiptScannerPlugin
        sharedDarwinSource: false
