// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_receipt_scanner_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> = listOf(result)

private fun wrapError(exception: Throwable): List<Any?> =
    if (exception is FlutterError) {
        listOf(
            exception.code,
            exception.message,
            exception.details,
        )
    } else {
        listOf(
            exception.javaClass.simpleName,
            exception.toString(),
            "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
        )
    }

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null,
) : Throwable()

enum class ScanSourceWire(
    val raw: Int,
) {
    CAMERA(0),
    GALLERY(1),
    ;

    companion object {
        fun ofRaw(raw: Int): ScanSourceWire? = values().firstOrNull { it.raw == raw }
    }
}

enum class ImageOriginWire(
    val raw: Int,
) {
    CAMERA(0),
    SCREENSHOT(1),
    DOWNLOAD(2),
    UNKNOWN(3),
    ;

    companion object {
        fun ofRaw(raw: Int): ImageOriginWire? = values().firstOrNull { it.raw == raw }
    }
}

enum class ScanStatusWire(
    val raw: Int,
) {
    SUCCESS(0),
    CANCELLED(1),
    REJECTED(2),
    ;

    companion object {
        fun ofRaw(raw: Int): ScanStatusWire? = values().firstOrNull { it.raw == raw }
    }
}

/**
 * Whether an OCR script model can run now or needs a download.
 *
 * Declared after the shipped wire classes on purpose — Pigeon assigns codec
 * bytes in declaration order.
 */
enum class OcrModelStatusWire(
    val raw: Int,
) {
    READY(0),
    DOWNLOAD_REQUIRED(1),
    ;

    companion object {
        fun ofRaw(raw: Int): OcrModelStatusWire? = values().firstOrNull { it.raw == raw }
    }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanOptionsWire(
    val source: ScanSourceWire? = null,
    val maxPages: Long? = null,
    val quality: Double? = null,
    val includeExif: Boolean? = null,
    val includeGpsExif: Boolean? = null,
    val ocr: Boolean? = null,
    val cropAutoConfirm: Boolean? = null,
    val autoRotate: Boolean? = null,
    val includeRawExif: Boolean? = null,
    val minimumTextHeight: Double? = null,
    val ocrGeometry: Boolean? = null,
    /**
     * Ordered BCP 47 language hints for on-device OCR. The app-facing package
     * always forwards a resolved list, so the native boundary is deterministic.
     */
    val ocrLanguages: List<String>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ScanOptionsWire {
            val source = pigeonVar_list[0] as ScanSourceWire?
            val maxPages = pigeonVar_list[1] as Long?
            val quality = pigeonVar_list[2] as Double?
            val includeExif = pigeonVar_list[3] as Boolean?
            val includeGpsExif = pigeonVar_list[4] as Boolean?
            val ocr = pigeonVar_list[5] as Boolean?
            val cropAutoConfirm = pigeonVar_list[6] as Boolean?
            val autoRotate = pigeonVar_list[7] as Boolean?
            val includeRawExif = pigeonVar_list[8] as Boolean?
            val minimumTextHeight = pigeonVar_list[9] as Double?
            val ocrGeometry = pigeonVar_list[10] as Boolean?
            val ocrLanguages = pigeonVar_list[11] as List<String>?
            return ScanOptionsWire(
                source,
                maxPages,
                quality,
                includeExif,
                includeGpsExif,
                ocr,
                cropAutoConfirm,
                autoRotate,
                includeRawExif,
                minimumTextHeight,
                ocrGeometry,
                ocrLanguages,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(
            source,
            maxPages,
            quality,
            includeExif,
            includeGpsExif,
            ocr,
            cropAutoConfirm,
            autoRotate,
            includeRawExif,
            minimumTextHeight,
            ocrGeometry,
            ocrLanguages,
        )
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GpsDataWire(
    val latitude: Double? = null,
    val longitude: Double? = null,
    val altitude: Double? = null,
    val timestamp: String? = null,
    val speed: Double? = null,
    val heading: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): GpsDataWire {
            val latitude = pigeonVar_list[0] as Double?
            val longitude = pigeonVar_list[1] as Double?
            val altitude = pigeonVar_list[2] as Double?
            val timestamp = pigeonVar_list[3] as String?
            val speed = pigeonVar_list[4] as Double?
            val heading = pigeonVar_list[5] as Double?
            return GpsDataWire(latitude, longitude, altitude, timestamp, speed, heading)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            latitude,
            longitude,
            altitude,
            timestamp,
            speed,
            heading,
        )
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptExifWire(
    val orientation: Long? = null,
    val colorSpace: Long? = null,
    val lightSource: Long? = null,
    val exifVersion: String? = null,
    val make: String? = null,
    val model: String? = null,
    val software: String? = null,
    val dateTime: String? = null,
    val dateTimeOriginal: String? = null,
    val dateTimeDigitized: String? = null,
    val exposureTime: Double? = null,
    val fNumber: Double? = null,
    val iso: Double? = null,
    val focalLength: Double? = null,
    val flash: Long? = null,
    val whiteBalance: Long? = null,
    val exposureMode: Long? = null,
    val exposureProgram: Long? = null,
    val meteringMode: Long? = null,
    val gps: GpsDataWire? = null,
    val raw: Map<String, Any?>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ReceiptExifWire {
            val orientation = pigeonVar_list[0] as Long?
            val colorSpace = pigeonVar_list[1] as Long?
            val lightSource = pigeonVar_list[2] as Long?
            val exifVersion = pigeonVar_list[3] as String?
            val make = pigeonVar_list[4] as String?
            val model = pigeonVar_list[5] as String?
            val software = pigeonVar_list[6] as String?
            val dateTime = pigeonVar_list[7] as String?
            val dateTimeOriginal = pigeonVar_list[8] as String?
            val dateTimeDigitized = pigeonVar_list[9] as String?
            val exposureTime = pigeonVar_list[10] as Double?
            val fNumber = pigeonVar_list[11] as Double?
            val iso = pigeonVar_list[12] as Double?
            val focalLength = pigeonVar_list[13] as Double?
            val flash = pigeonVar_list[14] as Long?
            val whiteBalance = pigeonVar_list[15] as Long?
            val exposureMode = pigeonVar_list[16] as Long?
            val exposureProgram = pigeonVar_list[17] as Long?
            val meteringMode = pigeonVar_list[18] as Long?
            val gps = pigeonVar_list[19] as GpsDataWire?
            val raw = pigeonVar_list[20] as Map<String, Any?>?
            return ReceiptExifWire(
                orientation,
                colorSpace,
                lightSource,
                exifVersion,
                make,
                model,
                software,
                dateTime,
                dateTimeOriginal,
                dateTimeDigitized,
                exposureTime,
                fNumber,
                iso,
                focalLength,
                flash,
                whiteBalance,
                exposureMode,
                exposureProgram,
                meteringMode,
                gps,
                raw,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(
            orientation,
            colorSpace,
            lightSource,
            exifVersion,
            make,
            model,
            software,
            dateTime,
            dateTimeOriginal,
            dateTimeDigitized,
            exposureTime,
            fNumber,
            iso,
            focalLength,
            flash,
            whiteBalance,
            exposureMode,
            exposureProgram,
            meteringMode,
            gps,
            raw,
        )
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrQualityWire(
    val textLength: Long? = null,
    val lineCount: Long? = null,
    val confidence: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrQualityWire {
            val textLength = pigeonVar_list[0] as Long?
            val lineCount = pigeonVar_list[1] as Long?
            val confidence = pigeonVar_list[2] as Double?
            return OcrQualityWire(textLength, lineCount, confidence)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            textLength,
            lineCount,
            confidence,
        )
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptImageWire(
    val uri: String,
    val width: Long,
    val height: Long,
    val fileName: String,
    val mimeType: String,
    val fileSize: Long,
    val imageOrigin: ImageOriginWire,
    val ocrText: String? = null,
    val ocrQuality: OcrQualityWire? = null,
    val exif: ReceiptExifWire? = null,
    val ocrLines: List<OcrLineWire>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ReceiptImageWire {
            val uri = pigeonVar_list[0] as String
            val width = pigeonVar_list[1] as Long
            val height = pigeonVar_list[2] as Long
            val fileName = pigeonVar_list[3] as String
            val mimeType = pigeonVar_list[4] as String
            val fileSize = pigeonVar_list[5] as Long
            val imageOrigin = pigeonVar_list[6] as ImageOriginWire
            val ocrText = pigeonVar_list[7] as String?
            val ocrQuality = pigeonVar_list[8] as OcrQualityWire?
            val exif = pigeonVar_list[9] as ReceiptExifWire?
            val ocrLines = pigeonVar_list[10] as List<OcrLineWire>?
            return ReceiptImageWire(uri, width, height, fileName, mimeType, fileSize, imageOrigin, ocrText, ocrQuality, exif, ocrLines)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            uri,
            width,
            height,
            fileName,
            mimeType,
            fileSize,
            imageOrigin,
            ocrText,
            ocrQuality,
            exif,
            ocrLines,
        )
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResultWire(
    val status: ScanStatusWire,
    val images: List<ReceiptImageWire>,
    val rejectedImages: List<ReceiptImageWire>,
    /**
     * Natively captured pages dropped before processing (absent means zero).
     * iOS can exceed `maxPages` because VisionKit cannot enforce a page limit
     * in its UI; declared last to keep existing wire positions stable.
     */
    val discardedPageCount: Long? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ScanResultWire {
            val status = pigeonVar_list[0] as ScanStatusWire
            val images = pigeonVar_list[1] as List<ReceiptImageWire>
            val rejectedImages = pigeonVar_list[2] as List<ReceiptImageWire>
            val discardedPageCount = pigeonVar_list[3] as Long?
            return ScanResultWire(status, images, rejectedImages, discardedPageCount)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            status,
            images,
            rejectedImages,
            discardedPageCount,
        )
}

/**
 * One recognized text line's box, in top-left-origin pixels of the output image.
 *
 * Declared after [ScanResultWire] on purpose: Pigeon assigns codec bytes in
 * declaration order, so new wire classes are appended at the end to keep the
 * byte assignments of already-shipped types stable.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrLineWire(
    val text: String,
    val x: Long,
    val y: Long,
    val width: Long,
    val height: Long,
    val confidence: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrLineWire {
            val text = pigeonVar_list[0] as String
            val x = pigeonVar_list[1] as Long
            val y = pigeonVar_list[2] as Long
            val width = pigeonVar_list[3] as Long
            val height = pigeonVar_list[4] as Long
            val confidence = pigeonVar_list[5] as Double?
            return OcrLineWire(text, x, y, width, height, confidence)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            text,
            x,
            y,
            width,
            height,
            confidence,
        )
}

/**
 * One script family's readiness, reported by Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrModelStateWire(
    /**
     * Unicode script identifier such as `Latn`, `Kore`, `Jpan`, `Hans`, `Hant`,
     * or `Deva`.
     */
    val script: String,
    val status: OcrModelStatusWire,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrModelStateWire {
            val script = pigeonVar_list[0] as String
            val status = pigeonVar_list[1] as OcrModelStatusWire
            return OcrModelStateWire(script, status)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            script,
            status,
        )
}

/**
 * Native OCR capability. `supportedLanguages` is iOS-only (Vision reports
 * exact identifiers); `models` is Android-only (ML Kit script families).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrCapabilitiesWire(
    val supportedLanguages: List<String>? = null,
    val models: List<OcrModelStateWire>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrCapabilitiesWire {
            val supportedLanguages = pigeonVar_list[0] as List<String>?
            val models = pigeonVar_list[1] as List<OcrModelStateWire>?
            return OcrCapabilitiesWire(supportedLanguages, models)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            supportedLanguages,
            models,
        )
}

private open class MessagesPigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(
        type: Byte,
        buffer: ByteBuffer,
    ): Any? {
        return when (type) {
            129.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ScanSourceWire.ofRaw(it.toInt())
                }
            }

            130.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ImageOriginWire.ofRaw(it.toInt())
                }
            }

            131.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ScanStatusWire.ofRaw(it.toInt())
                }
            }

            132.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    OcrModelStatusWire.ofRaw(it.toInt())
                }
            }

            133.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ScanOptionsWire.fromList(it)
                }
            }

            134.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    GpsDataWire.fromList(it)
                }
            }

            135.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ReceiptExifWire.fromList(it)
                }
            }

            136.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrQualityWire.fromList(it)
                }
            }

            137.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ReceiptImageWire.fromList(it)
                }
            }

            138.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ScanResultWire.fromList(it)
                }
            }

            139.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrLineWire.fromList(it)
                }
            }

            140.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrModelStateWire.fromList(it)
                }
            }

            141.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrCapabilitiesWire.fromList(it)
                }
            }

            else -> {
                super.readValueOfType(type, buffer)
            }
        }
    }

    override fun writeValue(
        stream: ByteArrayOutputStream,
        value: Any?,
    ) {
        when (value) {
            is ScanSourceWire -> {
                stream.write(129)
                writeValue(stream, value.raw)
            }

            is ImageOriginWire -> {
                stream.write(130)
                writeValue(stream, value.raw)
            }

            is ScanStatusWire -> {
                stream.write(131)
                writeValue(stream, value.raw)
            }

            is OcrModelStatusWire -> {
                stream.write(132)
                writeValue(stream, value.raw)
            }

            is ScanOptionsWire -> {
                stream.write(133)
                writeValue(stream, value.toList())
            }

            is GpsDataWire -> {
                stream.write(134)
                writeValue(stream, value.toList())
            }

            is ReceiptExifWire -> {
                stream.write(135)
                writeValue(stream, value.toList())
            }

            is OcrQualityWire -> {
                stream.write(136)
                writeValue(stream, value.toList())
            }

            is ReceiptImageWire -> {
                stream.write(137)
                writeValue(stream, value.toList())
            }

            is ScanResultWire -> {
                stream.write(138)
                writeValue(stream, value.toList())
            }

            is OcrLineWire -> {
                stream.write(139)
                writeValue(stream, value.toList())
            }

            is OcrModelStateWire -> {
                stream.write(140)
                writeValue(stream, value.toList())
            }

            is OcrCapabilitiesWire -> {
                stream.write(141)
                writeValue(stream, value.toList())
            }

            else -> {
                super.writeValue(stream, value)
            }
        }
    }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ReceiptScannerApi {
    fun scan(
        options: ScanOptionsWire,
        callback: (Result<ScanResultWire>) -> Unit,
    )

    /** Reports current OCR capability. Must not download a model or open UI. */
    fun getOcrCapabilities(callback: (Result<OcrCapabilitiesWire>) -> Unit)

    companion object {
        /** The codec used by ReceiptScannerApi. */
        val codec: MessageCodec<Any?> by lazy {
            MessagesPigeonCodec()
        }

        /** Sets up an instance of `ReceiptScannerApi` to handle messages through the `binaryMessenger`. */
        @JvmOverloads
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: ReceiptScannerApi?,
            messageChannelSuffix: String = "",
        ) {
            val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.scan$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val optionsArg = args[0] as ScanOptionsWire
                        api.scan(optionsArg) { result: Result<ScanResultWire> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.getOcrCapabilities$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        api.getOcrCapabilities { result: Result<OcrCapabilitiesWire> ->
                            val error = result.exceptionOrNull()
                            if (error != null) {
                                reply.reply(wrapError(error))
                            } else {
                                val data = result.getOrNull()
                                reply.reply(wrapResult(data))
                            }
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}
