// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.example.flutter_receipt_scanner_android

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException

private object MessagesPigeonUtils {
    fun wrapResult(result: Any?): List<Any?> = listOf(result)

    fun wrapError(exception: Throwable): List<Any?> =
        if (exception is FlutterError) {
            listOf(
                exception.code,
                exception.message,
                exception.details,
            )
        } else {
            listOf(
                exception.javaClass.simpleName,
                exception.toString(),
                "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception),
            )
        }

    fun doubleEquals(
        a: Double,
        b: Double,
    ): Boolean {
        // Normalize -0.0 to 0.0 and handle NaN equality.
        return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
    }

    fun floatEquals(
        a: Float,
        b: Float,
    ): Boolean {
        // Normalize -0.0 to 0.0 and handle NaN equality.
        return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
    }

    fun doubleHash(d: Double): Int {
        // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
        val normalized = if (d == 0.0) 0.0 else d
        val bits = java.lang.Double.doubleToLongBits(normalized)
        return (bits xor (bits ushr 32)).toInt()
    }

    fun floatHash(f: Float): Int {
        // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
        val normalized = if (f == 0.0f) 0.0f else f
        return java.lang.Float.floatToIntBits(normalized)
    }

    fun deepEquals(
        a: Any?,
        b: Any?,
    ): Boolean {
        if (a === b) {
            return true
        }
        if (a == null || b == null) {
            return false
        }
        if (a is ByteArray && b is ByteArray) {
            return a.contentEquals(b)
        }
        if (a is IntArray && b is IntArray) {
            return a.contentEquals(b)
        }
        if (a is LongArray && b is LongArray) {
            return a.contentEquals(b)
        }
        if (a is DoubleArray && b is DoubleArray) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!doubleEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is FloatArray && b is FloatArray) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!floatEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is Array<*> && b is Array<*>) {
            if (a.size != b.size) return false
            for (i in a.indices) {
                if (!deepEquals(a[i], b[i])) return false
            }
            return true
        }
        if (a is List<*> && b is List<*>) {
            if (a.size != b.size) return false
            val iterA = a.iterator()
            val iterB = b.iterator()
            while (iterA.hasNext() && iterB.hasNext()) {
                if (!deepEquals(iterA.next(), iterB.next())) return false
            }
            return true
        }
        if (a is Map<*, *> && b is Map<*, *>) {
            if (a.size != b.size) return false
            for (entry in a) {
                val key = entry.key
                var found = false
                for (bEntry in b) {
                    if (deepEquals(key, bEntry.key)) {
                        if (deepEquals(entry.value, bEntry.value)) {
                            found = true
                            break
                        } else {
                            return false
                        }
                    }
                }
                if (!found) return false
            }
            return true
        }
        if (a is Double && b is Double) {
            return doubleEquals(a, b)
        }
        if (a is Float && b is Float) {
            return floatEquals(a, b)
        }
        return a == b
    }

    fun deepHash(value: Any?): Int =
        when (value) {
            null -> {
                0
            }

            is ByteArray -> {
                value.contentHashCode()
            }

            is IntArray -> {
                value.contentHashCode()
            }

            is LongArray -> {
                value.contentHashCode()
            }

            is DoubleArray -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + doubleHash(item)
                }
                result
            }

            is FloatArray -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + floatHash(item)
                }
                result
            }

            is Array<*> -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + deepHash(item)
                }
                result
            }

            is List<*> -> {
                var result = 1
                for (item in value) {
                    result = 31 * result + deepHash(item)
                }
                result
            }

            is Map<*, *> -> {
                var result = 0
                for (entry in value) {
                    result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
                }
                result
            }

            is Double -> {
                doubleHash(value)
            }

            is Float -> {
                floatHash(value)
            }

            else -> {
                value.hashCode()
            }
        }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError(
    val code: String,
    override val message: String? = null,
    val details: Any? = null,
) : RuntimeException()

enum class ScanSourceWire(
    val raw: Int,
) {
    CAMERA(0),
    GALLERY(1),
    ;

    companion object {
        fun ofRaw(raw: Int): ScanSourceWire? = values().firstOrNull { it.raw == raw }
    }
}

enum class ImageOriginWire(
    val raw: Int,
) {
    CAMERA(0),
    SCREENSHOT(1),
    DOWNLOAD(2),
    UNKNOWN(3),
    ;

    companion object {
        fun ofRaw(raw: Int): ImageOriginWire? = values().firstOrNull { it.raw == raw }
    }
}

enum class ScanStatusWire(
    val raw: Int,
) {
    SUCCESS(0),
    CANCELLED(1),
    REJECTED(2),
    ;

    companion object {
        fun ofRaw(raw: Int): ScanStatusWire? = values().firstOrNull { it.raw == raw }
    }
}

/**
 * Whether an OCR script model can run now or needs a download.
 *
 * Declared after the shipped wire classes on purpose — Pigeon assigns codec
 * bytes in declaration order.
 */
enum class OcrModelStatusWire(
    val raw: Int,
) {
    READY(0),
    DOWNLOAD_REQUIRED(1),
    ;

    companion object {
        fun ofRaw(raw: Int): OcrModelStatusWire? = values().firstOrNull { it.raw == raw }
    }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanOptionsWire(
    val source: ScanSourceWire? = null,
    val maxPages: Long? = null,
    val quality: Double? = null,
    val includeExif: Boolean? = null,
    val includeGpsExif: Boolean? = null,
    val ocr: Boolean? = null,
    val cropAutoConfirm: Boolean? = null,
    val autoRotate: Boolean? = null,
    val includeRawExif: Boolean? = null,
    val minimumTextHeight: Double? = null,
    val ocrGeometry: Boolean? = null,
    /**
     * Ordered BCP 47 language hints for on-device OCR. The app-facing package
     * always forwards a resolved list, so the native boundary is deterministic.
     */
    val ocrLanguages: List<String>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ScanOptionsWire {
            val source = pigeonVar_list[0] as ScanSourceWire?
            val maxPages = pigeonVar_list[1] as Long?
            val quality = pigeonVar_list[2] as Double?
            val includeExif = pigeonVar_list[3] as Boolean?
            val includeGpsExif = pigeonVar_list[4] as Boolean?
            val ocr = pigeonVar_list[5] as Boolean?
            val cropAutoConfirm = pigeonVar_list[6] as Boolean?
            val autoRotate = pigeonVar_list[7] as Boolean?
            val includeRawExif = pigeonVar_list[8] as Boolean?
            val minimumTextHeight = pigeonVar_list[9] as Double?
            val ocrGeometry = pigeonVar_list[10] as Boolean?
            val ocrLanguages = pigeonVar_list[11] as List<String>?
            return ScanOptionsWire(
                source,
                maxPages,
                quality,
                includeExif,
                includeGpsExif,
                ocr,
                cropAutoConfirm,
                autoRotate,
                includeRawExif,
                minimumTextHeight,
                ocrGeometry,
                ocrLanguages,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(
            source,
            maxPages,
            quality,
            includeExif,
            includeGpsExif,
            ocr,
            cropAutoConfirm,
            autoRotate,
            includeRawExif,
            minimumTextHeight,
            ocrGeometry,
            ocrLanguages,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as ScanOptionsWire
        return MessagesPigeonUtils.deepEquals(this.source, other.source) && MessagesPigeonUtils.deepEquals(this.maxPages, other.maxPages) &&
            MessagesPigeonUtils.deepEquals(this.quality, other.quality) &&
            MessagesPigeonUtils.deepEquals(this.includeExif, other.includeExif) &&
            MessagesPigeonUtils.deepEquals(this.includeGpsExif, other.includeGpsExif) &&
            MessagesPigeonUtils.deepEquals(this.ocr, other.ocr) &&
            MessagesPigeonUtils.deepEquals(this.cropAutoConfirm, other.cropAutoConfirm) &&
            MessagesPigeonUtils.deepEquals(this.autoRotate, other.autoRotate) &&
            MessagesPigeonUtils.deepEquals(this.includeRawExif, other.includeRawExif) &&
            MessagesPigeonUtils.deepEquals(this.minimumTextHeight, other.minimumTextHeight) &&
            MessagesPigeonUtils.deepEquals(this.ocrGeometry, other.ocrGeometry) &&
            MessagesPigeonUtils.deepEquals(this.ocrLanguages, other.ocrLanguages)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.source)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.maxPages)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.includeExif)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.includeGpsExif)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocr)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.cropAutoConfirm)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.autoRotate)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.includeRawExif)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.minimumTextHeight)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocrGeometry)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocrLanguages)
        return result
    }

    override fun toString(): String =
        "ScanOptionsWire(source=$source, maxPages=$maxPages, quality=$quality, includeExif=$includeExif, includeGpsExif=$includeGpsExif, ocr=$ocr, cropAutoConfirm=$cropAutoConfirm, autoRotate=$autoRotate, includeRawExif=$includeRawExif, minimumTextHeight=$minimumTextHeight, ocrGeometry=$ocrGeometry, ocrLanguages=$ocrLanguages)"
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GpsDataWire(
    val latitude: Double? = null,
    val longitude: Double? = null,
    val altitude: Double? = null,
    val timestamp: String? = null,
    val speed: Double? = null,
    val heading: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): GpsDataWire {
            val latitude = pigeonVar_list[0] as Double?
            val longitude = pigeonVar_list[1] as Double?
            val altitude = pigeonVar_list[2] as Double?
            val timestamp = pigeonVar_list[3] as String?
            val speed = pigeonVar_list[4] as Double?
            val heading = pigeonVar_list[5] as Double?
            return GpsDataWire(latitude, longitude, altitude, timestamp, speed, heading)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            latitude,
            longitude,
            altitude,
            timestamp,
            speed,
            heading,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as GpsDataWire
        return MessagesPigeonUtils.deepEquals(
            this.latitude,
            other.latitude,
        ) && MessagesPigeonUtils.deepEquals(this.longitude, other.longitude) &&
            MessagesPigeonUtils.deepEquals(this.altitude, other.altitude) &&
            MessagesPigeonUtils.deepEquals(this.timestamp, other.timestamp) &&
            MessagesPigeonUtils.deepEquals(this.speed, other.speed) &&
            MessagesPigeonUtils.deepEquals(this.heading, other.heading)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.latitude)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.longitude)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.altitude)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.timestamp)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.speed)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.heading)
        return result
    }

    override fun toString(): String =
        "GpsDataWire(latitude=$latitude, longitude=$longitude, altitude=$altitude, timestamp=$timestamp, speed=$speed, heading=$heading)"
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptExifWire(
    val orientation: Long? = null,
    val colorSpace: Long? = null,
    val lightSource: Long? = null,
    val exifVersion: String? = null,
    val make: String? = null,
    val model: String? = null,
    val software: String? = null,
    val dateTime: String? = null,
    val dateTimeOriginal: String? = null,
    val dateTimeDigitized: String? = null,
    val exposureTime: Double? = null,
    val fNumber: Double? = null,
    val iso: Double? = null,
    val focalLength: Double? = null,
    val flash: Long? = null,
    val whiteBalance: Long? = null,
    val exposureMode: Long? = null,
    val exposureProgram: Long? = null,
    val meteringMode: Long? = null,
    val gps: GpsDataWire? = null,
    val raw: Map<String, Any?>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ReceiptExifWire {
            val orientation = pigeonVar_list[0] as Long?
            val colorSpace = pigeonVar_list[1] as Long?
            val lightSource = pigeonVar_list[2] as Long?
            val exifVersion = pigeonVar_list[3] as String?
            val make = pigeonVar_list[4] as String?
            val model = pigeonVar_list[5] as String?
            val software = pigeonVar_list[6] as String?
            val dateTime = pigeonVar_list[7] as String?
            val dateTimeOriginal = pigeonVar_list[8] as String?
            val dateTimeDigitized = pigeonVar_list[9] as String?
            val exposureTime = pigeonVar_list[10] as Double?
            val fNumber = pigeonVar_list[11] as Double?
            val iso = pigeonVar_list[12] as Double?
            val focalLength = pigeonVar_list[13] as Double?
            val flash = pigeonVar_list[14] as Long?
            val whiteBalance = pigeonVar_list[15] as Long?
            val exposureMode = pigeonVar_list[16] as Long?
            val exposureProgram = pigeonVar_list[17] as Long?
            val meteringMode = pigeonVar_list[18] as Long?
            val gps = pigeonVar_list[19] as GpsDataWire?
            val raw = pigeonVar_list[20] as Map<String, Any?>?
            return ReceiptExifWire(
                orientation,
                colorSpace,
                lightSource,
                exifVersion,
                make,
                model,
                software,
                dateTime,
                dateTimeOriginal,
                dateTimeDigitized,
                exposureTime,
                fNumber,
                iso,
                focalLength,
                flash,
                whiteBalance,
                exposureMode,
                exposureProgram,
                meteringMode,
                gps,
                raw,
            )
        }
    }

    fun toList(): List<Any?> =
        listOf(
            orientation,
            colorSpace,
            lightSource,
            exifVersion,
            make,
            model,
            software,
            dateTime,
            dateTimeOriginal,
            dateTimeDigitized,
            exposureTime,
            fNumber,
            iso,
            focalLength,
            flash,
            whiteBalance,
            exposureMode,
            exposureProgram,
            meteringMode,
            gps,
            raw,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as ReceiptExifWire
        return MessagesPigeonUtils.deepEquals(this.orientation, other.orientation) &&
            MessagesPigeonUtils.deepEquals(this.colorSpace, other.colorSpace) &&
            MessagesPigeonUtils.deepEquals(this.lightSource, other.lightSource) &&
            MessagesPigeonUtils.deepEquals(this.exifVersion, other.exifVersion) &&
            MessagesPigeonUtils.deepEquals(this.make, other.make) &&
            MessagesPigeonUtils.deepEquals(this.model, other.model) &&
            MessagesPigeonUtils.deepEquals(this.software, other.software) &&
            MessagesPigeonUtils.deepEquals(this.dateTime, other.dateTime) &&
            MessagesPigeonUtils.deepEquals(this.dateTimeOriginal, other.dateTimeOriginal) &&
            MessagesPigeonUtils.deepEquals(this.dateTimeDigitized, other.dateTimeDigitized) &&
            MessagesPigeonUtils.deepEquals(this.exposureTime, other.exposureTime) &&
            MessagesPigeonUtils.deepEquals(this.fNumber, other.fNumber) &&
            MessagesPigeonUtils.deepEquals(this.iso, other.iso) &&
            MessagesPigeonUtils.deepEquals(this.focalLength, other.focalLength) &&
            MessagesPigeonUtils.deepEquals(this.flash, other.flash) &&
            MessagesPigeonUtils.deepEquals(this.whiteBalance, other.whiteBalance) &&
            MessagesPigeonUtils.deepEquals(this.exposureMode, other.exposureMode) &&
            MessagesPigeonUtils.deepEquals(this.exposureProgram, other.exposureProgram) &&
            MessagesPigeonUtils.deepEquals(this.meteringMode, other.meteringMode) &&
            MessagesPigeonUtils.deepEquals(this.gps, other.gps) &&
            MessagesPigeonUtils.deepEquals(this.raw, other.raw)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.orientation)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.colorSpace)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.lightSource)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.exifVersion)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.make)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.model)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.software)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTime)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTimeOriginal)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.dateTimeDigitized)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.exposureTime)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.fNumber)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.iso)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.focalLength)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.flash)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.whiteBalance)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.exposureMode)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.exposureProgram)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.meteringMode)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.gps)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.raw)
        return result
    }

    override fun toString(): String =
        "ReceiptExifWire(orientation=$orientation, colorSpace=$colorSpace, lightSource=$lightSource, exifVersion=$exifVersion, make=$make, model=$model, software=$software, dateTime=$dateTime, dateTimeOriginal=$dateTimeOriginal, dateTimeDigitized=$dateTimeDigitized, exposureTime=$exposureTime, fNumber=$fNumber, iso=$iso, focalLength=$focalLength, flash=$flash, whiteBalance=$whiteBalance, exposureMode=$exposureMode, exposureProgram=$exposureProgram, meteringMode=$meteringMode, gps=$gps, raw=$raw)"
}

/** Generated class from Pigeon that represents data sent in messages. */
data class OcrQualityWire(
    val textLength: Long? = null,
    val lineCount: Long? = null,
    val confidence: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrQualityWire {
            val textLength = pigeonVar_list[0] as Long?
            val lineCount = pigeonVar_list[1] as Long?
            val confidence = pigeonVar_list[2] as Double?
            return OcrQualityWire(textLength, lineCount, confidence)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            textLength,
            lineCount,
            confidence,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as OcrQualityWire
        return MessagesPigeonUtils.deepEquals(this.textLength, other.textLength) &&
            MessagesPigeonUtils.deepEquals(this.lineCount, other.lineCount) &&
            MessagesPigeonUtils.deepEquals(this.confidence, other.confidence)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.textLength)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.lineCount)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.confidence)
        return result
    }

    override fun toString(): String = "OcrQualityWire(textLength=$textLength, lineCount=$lineCount, confidence=$confidence)"
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ReceiptImageWire(
    val uri: String,
    val width: Long,
    val height: Long,
    val fileName: String,
    val mimeType: String,
    val fileSize: Long,
    val imageOrigin: ImageOriginWire,
    val ocrText: String? = null,
    val ocrQuality: OcrQualityWire? = null,
    val exif: ReceiptExifWire? = null,
    val ocrLines: List<OcrLineWire>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ReceiptImageWire {
            val uri = pigeonVar_list[0] as String
            val width = pigeonVar_list[1] as Long
            val height = pigeonVar_list[2] as Long
            val fileName = pigeonVar_list[3] as String
            val mimeType = pigeonVar_list[4] as String
            val fileSize = pigeonVar_list[5] as Long
            val imageOrigin = pigeonVar_list[6] as ImageOriginWire
            val ocrText = pigeonVar_list[7] as String?
            val ocrQuality = pigeonVar_list[8] as OcrQualityWire?
            val exif = pigeonVar_list[9] as ReceiptExifWire?
            val ocrLines = pigeonVar_list[10] as List<OcrLineWire>?
            return ReceiptImageWire(uri, width, height, fileName, mimeType, fileSize, imageOrigin, ocrText, ocrQuality, exif, ocrLines)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            uri,
            width,
            height,
            fileName,
            mimeType,
            fileSize,
            imageOrigin,
            ocrText,
            ocrQuality,
            exif,
            ocrLines,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as ReceiptImageWire
        return MessagesPigeonUtils.deepEquals(this.uri, other.uri) && MessagesPigeonUtils.deepEquals(this.width, other.width) &&
            MessagesPigeonUtils.deepEquals(this.height, other.height) &&
            MessagesPigeonUtils.deepEquals(this.fileName, other.fileName) &&
            MessagesPigeonUtils.deepEquals(this.mimeType, other.mimeType) &&
            MessagesPigeonUtils.deepEquals(this.fileSize, other.fileSize) &&
            MessagesPigeonUtils.deepEquals(this.imageOrigin, other.imageOrigin) &&
            MessagesPigeonUtils.deepEquals(this.ocrText, other.ocrText) &&
            MessagesPigeonUtils.deepEquals(this.ocrQuality, other.ocrQuality) &&
            MessagesPigeonUtils.deepEquals(this.exif, other.exif) &&
            MessagesPigeonUtils.deepEquals(this.ocrLines, other.ocrLines)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.uri)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.fileName)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.mimeType)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.fileSize)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.imageOrigin)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocrText)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocrQuality)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.exif)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.ocrLines)
        return result
    }

    override fun toString(): String =
        "ReceiptImageWire(uri=$uri, width=$width, height=$height, fileName=$fileName, mimeType=$mimeType, fileSize=$fileSize, imageOrigin=$imageOrigin, ocrText=$ocrText, ocrQuality=$ocrQuality, exif=$exif, ocrLines=$ocrLines)"
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ScanResultWire(
    val status: ScanStatusWire,
    val images: List<ReceiptImageWire>,
    val rejectedImages: List<ReceiptImageWire>,
    /**
     * Natively captured pages dropped before processing (absent means zero).
     * iOS can exceed `maxPages` because VisionKit cannot enforce a page limit
     * in its UI; declared last to keep existing wire positions stable.
     */
    val discardedPageCount: Long? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): ScanResultWire {
            val status = pigeonVar_list[0] as ScanStatusWire
            val images = pigeonVar_list[1] as List<ReceiptImageWire>
            val rejectedImages = pigeonVar_list[2] as List<ReceiptImageWire>
            val discardedPageCount = pigeonVar_list[3] as Long?
            return ScanResultWire(status, images, rejectedImages, discardedPageCount)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            status,
            images,
            rejectedImages,
            discardedPageCount,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as ScanResultWire
        return MessagesPigeonUtils.deepEquals(this.status, other.status) && MessagesPigeonUtils.deepEquals(this.images, other.images) &&
            MessagesPigeonUtils.deepEquals(this.rejectedImages, other.rejectedImages) &&
            MessagesPigeonUtils.deepEquals(this.discardedPageCount, other.discardedPageCount)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.images)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.rejectedImages)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.discardedPageCount)
        return result
    }

    override fun toString(): String =
        "ScanResultWire(status=$status, images=$images, rejectedImages=$rejectedImages, discardedPageCount=$discardedPageCount)"
}

/**
 * One recognized text line's box, in top-left-origin pixels of the output image.
 *
 * Declared after [ScanResultWire] on purpose: Pigeon assigns codec bytes in
 * declaration order, so new wire classes are appended at the end to keep the
 * byte assignments of already-shipped types stable.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrLineWire(
    val text: String,
    val x: Long,
    val y: Long,
    val width: Long,
    val height: Long,
    val confidence: Double? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrLineWire {
            val text = pigeonVar_list[0] as String
            val x = pigeonVar_list[1] as Long
            val y = pigeonVar_list[2] as Long
            val width = pigeonVar_list[3] as Long
            val height = pigeonVar_list[4] as Long
            val confidence = pigeonVar_list[5] as Double?
            return OcrLineWire(text, x, y, width, height, confidence)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            text,
            x,
            y,
            width,
            height,
            confidence,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as OcrLineWire
        return MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.x, other.x) &&
            MessagesPigeonUtils.deepEquals(this.y, other.y) &&
            MessagesPigeonUtils.deepEquals(this.width, other.width) &&
            MessagesPigeonUtils.deepEquals(this.height, other.height) &&
            MessagesPigeonUtils.deepEquals(this.confidence, other.confidence)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.x)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.y)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.confidence)
        return result
    }

    override fun toString(): String = "OcrLineWire(text=$text, x=$x, y=$y, width=$width, height=$height, confidence=$confidence)"
}

/**
 * One script family's readiness, reported by Android.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrModelStateWire(
    /**
     * Unicode script identifier such as `Latn`, `Kore`, `Jpan`, `Hans`, `Hant`,
     * or `Deva`.
     */
    val script: String,
    val status: OcrModelStatusWire,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrModelStateWire {
            val script = pigeonVar_list[0] as String
            val status = pigeonVar_list[1] as OcrModelStatusWire
            return OcrModelStateWire(script, status)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            script,
            status,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as OcrModelStateWire
        return MessagesPigeonUtils.deepEquals(this.script, other.script) && MessagesPigeonUtils.deepEquals(this.status, other.status)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.script)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.status)
        return result
    }

    override fun toString(): String = "OcrModelStateWire(script=$script, status=$status)"
}

/**
 * Native OCR capability. `supportedLanguages` is iOS-only (Vision reports
 * exact identifiers); `models` is Android-only (ML Kit script families).
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class OcrCapabilitiesWire(
    val supportedLanguages: List<String>? = null,
    val models: List<OcrModelStateWire>? = null,
) {
    companion object {
        fun fromList(pigeonVar_list: List<Any?>): OcrCapabilitiesWire {
            val supportedLanguages = pigeonVar_list[0] as List<String>?
            val models = pigeonVar_list[1] as List<OcrModelStateWire>?
            return OcrCapabilitiesWire(supportedLanguages, models)
        }
    }

    fun toList(): List<Any?> =
        listOf(
            supportedLanguages,
            models,
        )

    override fun equals(other: Any?): Boolean {
        if (other == null || other.javaClass != javaClass) {
            return false
        }
        if (this === other) {
            return true
        }
        val other = other as OcrCapabilitiesWire
        return MessagesPigeonUtils.deepEquals(this.supportedLanguages, other.supportedLanguages) &&
            MessagesPigeonUtils.deepEquals(this.models, other.models)
    }

    override fun hashCode(): Int {
        var result = javaClass.hashCode()
        result = 31 * result + MessagesPigeonUtils.deepHash(this.supportedLanguages)
        result = 31 * result + MessagesPigeonUtils.deepHash(this.models)
        return result
    }

    override fun toString(): String = "OcrCapabilitiesWire(supportedLanguages=$supportedLanguages, models=$models)"
}

private open class MessagesPigeonCodec : StandardMessageCodec() {
    override fun readValueOfType(
        type: Byte,
        buffer: ByteBuffer,
    ): Any? {
        return when (type) {
            129.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ScanSourceWire.ofRaw(it.toInt())
                }
            }

            130.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ImageOriginWire.ofRaw(it.toInt())
                }
            }

            131.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    ScanStatusWire.ofRaw(it.toInt())
                }
            }

            132.toByte() -> {
                return (readValue(buffer) as Long?)?.let {
                    OcrModelStatusWire.ofRaw(it.toInt())
                }
            }

            133.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ScanOptionsWire.fromList(it)
                }
            }

            134.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    GpsDataWire.fromList(it)
                }
            }

            135.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ReceiptExifWire.fromList(it)
                }
            }

            136.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrQualityWire.fromList(it)
                }
            }

            137.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ReceiptImageWire.fromList(it)
                }
            }

            138.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    ScanResultWire.fromList(it)
                }
            }

            139.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrLineWire.fromList(it)
                }
            }

            140.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrModelStateWire.fromList(it)
                }
            }

            141.toByte() -> {
                return (readValue(buffer) as? List<Any?>)?.let {
                    OcrCapabilitiesWire.fromList(it)
                }
            }

            else -> {
                super.readValueOfType(type, buffer)
            }
        }
    }

    override fun writeValue(
        stream: ByteArrayOutputStream,
        value: Any?,
    ) {
        when (value) {
            is ScanSourceWire -> {
                stream.write(129)
                writeValue(stream, value.raw.toLong())
            }

            is ImageOriginWire -> {
                stream.write(130)
                writeValue(stream, value.raw.toLong())
            }

            is ScanStatusWire -> {
                stream.write(131)
                writeValue(stream, value.raw.toLong())
            }

            is OcrModelStatusWire -> {
                stream.write(132)
                writeValue(stream, value.raw.toLong())
            }

            is ScanOptionsWire -> {
                stream.write(133)
                writeValue(stream, value.toList())
            }

            is GpsDataWire -> {
                stream.write(134)
                writeValue(stream, value.toList())
            }

            is ReceiptExifWire -> {
                stream.write(135)
                writeValue(stream, value.toList())
            }

            is OcrQualityWire -> {
                stream.write(136)
                writeValue(stream, value.toList())
            }

            is ReceiptImageWire -> {
                stream.write(137)
                writeValue(stream, value.toList())
            }

            is ScanResultWire -> {
                stream.write(138)
                writeValue(stream, value.toList())
            }

            is OcrLineWire -> {
                stream.write(139)
                writeValue(stream, value.toList())
            }

            is OcrModelStateWire -> {
                stream.write(140)
                writeValue(stream, value.toList())
            }

            is OcrCapabilitiesWire -> {
                stream.write(141)
                writeValue(stream, value.toList())
            }

            else -> {
                super.writeValue(stream, value)
            }
        }
    }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface ReceiptScannerApi {
    suspend fun scan(options: ScanOptionsWire): ScanResultWire

    /** Reports current OCR capability. Must not download a model or open UI. */
    suspend fun getOcrCapabilities(): OcrCapabilitiesWire

    companion object {
        /** The codec used by ReceiptScannerApi. */
        val codec: MessageCodec<Any?> by lazy {
            MessagesPigeonCodec()
        }

        /** Sets up an instance of `ReceiptScannerApi` to handle messages through the `binaryMessenger`. */
        @JvmOverloads
        fun setUp(
            binaryMessenger: BinaryMessenger,
            api: ReceiptScannerApi?,
            messageChannelSuffix: String = "",
        ) {
            val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.scan$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { message, reply ->
                        val args = message as List<Any?>
                        val optionsArg = args[0] as ScanOptionsWire
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    listOf(api.scan(optionsArg))
                                } catch (exception: Throwable) {
                                    MessagesPigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
            run {
                val channel =
                    BasicMessageChannel<Any?>(
                        binaryMessenger,
                        "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.getOcrCapabilities$separatedMessageChannelSuffix",
                        codec,
                    )
                if (api != null) {
                    channel.setMessageHandler { _, reply ->
                        CoroutineScope(Dispatchers.Main).launch {
                            val wrapped: List<Any?> =
                                try {
                                    listOf(api.getOcrCapabilities())
                                } catch (exception: Throwable) {
                                    MessagesPigeonUtils.wrapError(exception)
                                }
                            reply.reply(wrapped)
                        }
                    }
                } else {
                    channel.setMessageHandler(null)
                }
            }
        }
    }
}
