// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
    import Flutter
#elseif os(macOS)
    import FlutterMacOS
#else
    #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
    let code: String
    let message: String?
    let details: Any?

    init(code: String, message: String?, details: Any?) {
        self.code = code
        self.message = message
        self.details = details
    }

    var localizedDescription: String {
        return
            "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
    }
}

private func wrapResult(_ result: Any?) -> [Any?] {
    return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
    if let pigeonError = error as? PigeonError {
        return [
            pigeonError.code,
            pigeonError.message,
            pigeonError.details,
        ]
    }
    if let flutterError = error as? FlutterError {
        return [
            flutterError.code,
            flutterError.message,
            flutterError.details,
        ]
    }
    return [
        "\(error)",
        "\(type(of: error))",
        "Stacktrace: \(Thread.callStackSymbols)",
    ]
}

private func isNullish(_ value: Any?) -> Bool {
    return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
    if value is NSNull { return nil }
    return value as! T?
}

enum ScanSourceWire: Int {
    case camera = 0
    case gallery = 1
}

enum ImageOriginWire: Int {
    case camera = 0
    case screenshot = 1
    case download = 2
    case unknown = 3
}

enum ScanStatusWire: Int {
    case success = 0
    case cancelled = 1
    case rejected = 2
}

/// Whether an OCR script model can run now or needs a download.
///
/// Declared after the shipped wire classes on purpose — Pigeon assigns codec
/// bytes in declaration order.
enum OcrModelStatusWire: Int {
    case ready = 0
    case downloadRequired = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanOptionsWire {
    var source: ScanSourceWire? = nil
    var maxPages: Int64? = nil
    var quality: Double? = nil
    var includeExif: Bool? = nil
    var includeGpsExif: Bool? = nil
    var ocr: Bool? = nil
    var cropAutoConfirm: Bool? = nil
    var autoRotate: Bool? = nil
    var includeRawExif: Bool? = nil
    var minimumTextHeight: Double? = nil
    var ocrGeometry: Bool? = nil
    /// Ordered BCP 47 language hints for on-device OCR. The app-facing package
    /// always forwards a resolved list, so the native boundary is deterministic.
    var ocrLanguages: [String]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ScanOptionsWire? {
        let source: ScanSourceWire? = nilOrValue(pigeonVar_list[0])
        let maxPages: Int64? = nilOrValue(pigeonVar_list[1])
        let quality: Double? = nilOrValue(pigeonVar_list[2])
        let includeExif: Bool? = nilOrValue(pigeonVar_list[3])
        let includeGpsExif: Bool? = nilOrValue(pigeonVar_list[4])
        let ocr: Bool? = nilOrValue(pigeonVar_list[5])
        let cropAutoConfirm: Bool? = nilOrValue(pigeonVar_list[6])
        let autoRotate: Bool? = nilOrValue(pigeonVar_list[7])
        let includeRawExif: Bool? = nilOrValue(pigeonVar_list[8])
        let minimumTextHeight: Double? = nilOrValue(pigeonVar_list[9])
        let ocrGeometry: Bool? = nilOrValue(pigeonVar_list[10])
        let ocrLanguages: [String]? = nilOrValue(pigeonVar_list[11])

        return ScanOptionsWire(
            source: source,
            maxPages: maxPages,
            quality: quality,
            includeExif: includeExif,
            includeGpsExif: includeGpsExif,
            ocr: ocr,
            cropAutoConfirm: cropAutoConfirm,
            autoRotate: autoRotate,
            includeRawExif: includeRawExif,
            minimumTextHeight: minimumTextHeight,
            ocrGeometry: ocrGeometry,
            ocrLanguages: ocrLanguages
        )
    }

    func toList() -> [Any?] {
        return [
            source,
            maxPages,
            quality,
            includeExif,
            includeGpsExif,
            ocr,
            cropAutoConfirm,
            autoRotate,
            includeRawExif,
            minimumTextHeight,
            ocrGeometry,
            ocrLanguages,
        ]
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GpsDataWire {
    var latitude: Double? = nil
    var longitude: Double? = nil
    var altitude: Double? = nil
    var timestamp: String? = nil
    var speed: Double? = nil
    var heading: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> GpsDataWire? {
        let latitude: Double? = nilOrValue(pigeonVar_list[0])
        let longitude: Double? = nilOrValue(pigeonVar_list[1])
        let altitude: Double? = nilOrValue(pigeonVar_list[2])
        let timestamp: String? = nilOrValue(pigeonVar_list[3])
        let speed: Double? = nilOrValue(pigeonVar_list[4])
        let heading: Double? = nilOrValue(pigeonVar_list[5])

        return GpsDataWire(
            latitude: latitude,
            longitude: longitude,
            altitude: altitude,
            timestamp: timestamp,
            speed: speed,
            heading: heading
        )
    }

    func toList() -> [Any?] {
        return [
            latitude,
            longitude,
            altitude,
            timestamp,
            speed,
            heading,
        ]
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiptExifWire {
    var orientation: Int64? = nil
    var colorSpace: Int64? = nil
    var lightSource: Int64? = nil
    var exifVersion: String? = nil
    var make: String? = nil
    var model: String? = nil
    var software: String? = nil
    var dateTime: String? = nil
    var dateTimeOriginal: String? = nil
    var dateTimeDigitized: String? = nil
    var exposureTime: Double? = nil
    var fNumber: Double? = nil
    var iso: Double? = nil
    var focalLength: Double? = nil
    var flash: Int64? = nil
    var whiteBalance: Int64? = nil
    var exposureMode: Int64? = nil
    var exposureProgram: Int64? = nil
    var meteringMode: Int64? = nil
    var gps: GpsDataWire? = nil
    var raw: [String: Any?]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ReceiptExifWire? {
        let orientation: Int64? = nilOrValue(pigeonVar_list[0])
        let colorSpace: Int64? = nilOrValue(pigeonVar_list[1])
        let lightSource: Int64? = nilOrValue(pigeonVar_list[2])
        let exifVersion: String? = nilOrValue(pigeonVar_list[3])
        let make: String? = nilOrValue(pigeonVar_list[4])
        let model: String? = nilOrValue(pigeonVar_list[5])
        let software: String? = nilOrValue(pigeonVar_list[6])
        let dateTime: String? = nilOrValue(pigeonVar_list[7])
        let dateTimeOriginal: String? = nilOrValue(pigeonVar_list[8])
        let dateTimeDigitized: String? = nilOrValue(pigeonVar_list[9])
        let exposureTime: Double? = nilOrValue(pigeonVar_list[10])
        let fNumber: Double? = nilOrValue(pigeonVar_list[11])
        let iso: Double? = nilOrValue(pigeonVar_list[12])
        let focalLength: Double? = nilOrValue(pigeonVar_list[13])
        let flash: Int64? = nilOrValue(pigeonVar_list[14])
        let whiteBalance: Int64? = nilOrValue(pigeonVar_list[15])
        let exposureMode: Int64? = nilOrValue(pigeonVar_list[16])
        let exposureProgram: Int64? = nilOrValue(pigeonVar_list[17])
        let meteringMode: Int64? = nilOrValue(pigeonVar_list[18])
        let gps: GpsDataWire? = nilOrValue(pigeonVar_list[19])
        let raw: [String: Any?]? = nilOrValue(pigeonVar_list[20])

        return ReceiptExifWire(
            orientation: orientation,
            colorSpace: colorSpace,
            lightSource: lightSource,
            exifVersion: exifVersion,
            make: make,
            model: model,
            software: software,
            dateTime: dateTime,
            dateTimeOriginal: dateTimeOriginal,
            dateTimeDigitized: dateTimeDigitized,
            exposureTime: exposureTime,
            fNumber: fNumber,
            iso: iso,
            focalLength: focalLength,
            flash: flash,
            whiteBalance: whiteBalance,
            exposureMode: exposureMode,
            exposureProgram: exposureProgram,
            meteringMode: meteringMode,
            gps: gps,
            raw: raw
        )
    }

    func toList() -> [Any?] {
        return [
            orientation,
            colorSpace,
            lightSource,
            exifVersion,
            make,
            model,
            software,
            dateTime,
            dateTimeOriginal,
            dateTimeDigitized,
            exposureTime,
            fNumber,
            iso,
            focalLength,
            flash,
            whiteBalance,
            exposureMode,
            exposureProgram,
            meteringMode,
            gps,
            raw,
        ]
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OcrQualityWire {
    var textLength: Int64? = nil
    var lineCount: Int64? = nil
    var confidence: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrQualityWire? {
        let textLength: Int64? = nilOrValue(pigeonVar_list[0])
        let lineCount: Int64? = nilOrValue(pigeonVar_list[1])
        let confidence: Double? = nilOrValue(pigeonVar_list[2])

        return OcrQualityWire(
            textLength: textLength,
            lineCount: lineCount,
            confidence: confidence
        )
    }

    func toList() -> [Any?] {
        return [
            textLength,
            lineCount,
            confidence,
        ]
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiptImageWire {
    var uri: String
    var width: Int64
    var height: Int64
    var fileName: String
    var mimeType: String
    var fileSize: Int64
    var imageOrigin: ImageOriginWire
    var ocrText: String? = nil
    var ocrQuality: OcrQualityWire? = nil
    var exif: ReceiptExifWire? = nil
    var ocrLines: [OcrLineWire]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ReceiptImageWire? {
        let uri = pigeonVar_list[0] as! String
        let width = pigeonVar_list[1] as! Int64
        let height = pigeonVar_list[2] as! Int64
        let fileName = pigeonVar_list[3] as! String
        let mimeType = pigeonVar_list[4] as! String
        let fileSize = pigeonVar_list[5] as! Int64
        let imageOrigin = pigeonVar_list[6] as! ImageOriginWire
        let ocrText: String? = nilOrValue(pigeonVar_list[7])
        let ocrQuality: OcrQualityWire? = nilOrValue(pigeonVar_list[8])
        let exif: ReceiptExifWire? = nilOrValue(pigeonVar_list[9])
        let ocrLines: [OcrLineWire]? = nilOrValue(pigeonVar_list[10])

        return ReceiptImageWire(
            uri: uri,
            width: width,
            height: height,
            fileName: fileName,
            mimeType: mimeType,
            fileSize: fileSize,
            imageOrigin: imageOrigin,
            ocrText: ocrText,
            ocrQuality: ocrQuality,
            exif: exif,
            ocrLines: ocrLines
        )
    }

    func toList() -> [Any?] {
        return [
            uri,
            width,
            height,
            fileName,
            mimeType,
            fileSize,
            imageOrigin,
            ocrText,
            ocrQuality,
            exif,
            ocrLines,
        ]
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanResultWire {
    var status: ScanStatusWire
    var images: [ReceiptImageWire]
    var rejectedImages: [ReceiptImageWire]
    /// Natively captured pages dropped before processing (absent means zero).
    /// iOS can exceed `maxPages` because VisionKit cannot enforce a page limit
    /// in its UI; declared last to keep existing wire positions stable.
    var discardedPageCount: Int64? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ScanResultWire? {
        let status = pigeonVar_list[0] as! ScanStatusWire
        let images = pigeonVar_list[1] as! [ReceiptImageWire]
        let rejectedImages = pigeonVar_list[2] as! [ReceiptImageWire]
        let discardedPageCount: Int64? = nilOrValue(pigeonVar_list[3])

        return ScanResultWire(
            status: status,
            images: images,
            rejectedImages: rejectedImages,
            discardedPageCount: discardedPageCount
        )
    }

    func toList() -> [Any?] {
        return [
            status,
            images,
            rejectedImages,
            discardedPageCount,
        ]
    }
}

/// One recognized text line's box, in top-left-origin pixels of the output image.
///
/// Declared after [ScanResultWire] on purpose: Pigeon assigns codec bytes in
/// declaration order, so new wire classes are appended at the end to keep the
/// byte assignments of already-shipped types stable.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrLineWire {
    var text: String
    var x: Int64
    var y: Int64
    var width: Int64
    var height: Int64
    var confidence: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrLineWire? {
        let text = pigeonVar_list[0] as! String
        let x = pigeonVar_list[1] as! Int64
        let y = pigeonVar_list[2] as! Int64
        let width = pigeonVar_list[3] as! Int64
        let height = pigeonVar_list[4] as! Int64
        let confidence: Double? = nilOrValue(pigeonVar_list[5])

        return OcrLineWire(
            text: text,
            x: x,
            y: y,
            width: width,
            height: height,
            confidence: confidence
        )
    }

    func toList() -> [Any?] {
        return [
            text,
            x,
            y,
            width,
            height,
            confidence,
        ]
    }
}

/// One script family's readiness, reported by Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrModelStateWire {
    /// Unicode script identifier such as `Latn`, `Kore`, `Jpan`, `Hans`, `Hant`,
    /// or `Deva`.
    var script: String
    var status: OcrModelStatusWire

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrModelStateWire? {
        let script = pigeonVar_list[0] as! String
        let status = pigeonVar_list[1] as! OcrModelStatusWire

        return OcrModelStateWire(
            script: script,
            status: status
        )
    }

    func toList() -> [Any?] {
        return [
            script,
            status,
        ]
    }
}

/// Native OCR capability. `supportedLanguages` is iOS-only (Vision reports
/// exact identifiers); `models` is Android-only (ML Kit script families).
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrCapabilitiesWire {
    var supportedLanguages: [String]? = nil
    var models: [OcrModelStateWire]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrCapabilitiesWire? {
        let supportedLanguages: [String]? = nilOrValue(pigeonVar_list[0])
        let models: [OcrModelStateWire]? = nilOrValue(pigeonVar_list[1])

        return OcrCapabilitiesWire(
            supportedLanguages: supportedLanguages,
            models: models
        )
    }

    func toList() -> [Any?] {
        return [
            supportedLanguages,
            models,
        ]
    }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 129:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ScanSourceWire(rawValue: enumResultAsInt)
            }
            return nil
        case 130:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ImageOriginWire(rawValue: enumResultAsInt)
            }
            return nil
        case 131:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ScanStatusWire(rawValue: enumResultAsInt)
            }
            return nil
        case 132:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return OcrModelStatusWire(rawValue: enumResultAsInt)
            }
            return nil
        case 133:
            return ScanOptionsWire.fromList(readValue() as! [Any?])
        case 134:
            return GpsDataWire.fromList(readValue() as! [Any?])
        case 135:
            return ReceiptExifWire.fromList(readValue() as! [Any?])
        case 136:
            return OcrQualityWire.fromList(readValue() as! [Any?])
        case 137:
            return ReceiptImageWire.fromList(readValue() as! [Any?])
        case 138:
            return ScanResultWire.fromList(readValue() as! [Any?])
        case 139:
            return OcrLineWire.fromList(readValue() as! [Any?])
        case 140:
            return OcrModelStateWire.fromList(readValue() as! [Any?])
        case 141:
            return OcrCapabilitiesWire.fromList(readValue() as! [Any?])
        default:
            return super.readValue(ofType: type)
        }
    }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let value = value as? ScanSourceWire {
            super.writeByte(129)
            super.writeValue(value.rawValue)
        } else if let value = value as? ImageOriginWire {
            super.writeByte(130)
            super.writeValue(value.rawValue)
        } else if let value = value as? ScanStatusWire {
            super.writeByte(131)
            super.writeValue(value.rawValue)
        } else if let value = value as? OcrModelStatusWire {
            super.writeByte(132)
            super.writeValue(value.rawValue)
        } else if let value = value as? ScanOptionsWire {
            super.writeByte(133)
            super.writeValue(value.toList())
        } else if let value = value as? GpsDataWire {
            super.writeByte(134)
            super.writeValue(value.toList())
        } else if let value = value as? ReceiptExifWire {
            super.writeByte(135)
            super.writeValue(value.toList())
        } else if let value = value as? OcrQualityWire {
            super.writeByte(136)
            super.writeValue(value.toList())
        } else if let value = value as? ReceiptImageWire {
            super.writeByte(137)
            super.writeValue(value.toList())
        } else if let value = value as? ScanResultWire {
            super.writeByte(138)
            super.writeValue(value.toList())
        } else if let value = value as? OcrLineWire {
            super.writeByte(139)
            super.writeValue(value.toList())
        } else if let value = value as? OcrModelStateWire {
            super.writeByte(140)
            super.writeValue(value.toList())
        } else if let value = value as? OcrCapabilitiesWire {
            super.writeByte(141)
            super.writeValue(value.toList())
        } else {
            super.writeValue(value)
        }
    }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader {
        return MessagesPigeonCodecReader(data: data)
    }

    override func writer(with data: NSMutableData) -> FlutterStandardWriter {
        return MessagesPigeonCodecWriter(data: data)
    }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
    static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReceiptScannerApi {
    func scan(options: ScanOptionsWire, completion: @escaping (Result<ScanResultWire, Error>) -> Void)
    /// Reports current OCR capability. Must not download a model or open UI.
    func getOcrCapabilities(completion: @escaping (Result<OcrCapabilitiesWire, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReceiptScannerApiSetup {
    static var codec: FlutterStandardMessageCodec {
        MessagesPigeonCodec.shared
    }

    /// Sets up an instance of `ReceiptScannerApi` to handle messages through the `binaryMessenger`.
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReceiptScannerApi?, messageChannelSuffix: String = "") {
        let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
        let scanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.scan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            scanChannel.setMessageHandler { message, reply in
                let args = message as! [Any?]
                let optionsArg = args[0] as! ScanOptionsWire
                api.scan(options: optionsArg) { result in
                    switch result {
                    case let .success(res):
                        reply(wrapResult(res))
                    case let .failure(error):
                        reply(wrapError(error))
                    }
                }
            }
        } else {
            scanChannel.setMessageHandler(nil)
        }
        // Reports current OCR capability. Must not download a model or open UI.
        let getOcrCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.getOcrCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            getOcrCapabilitiesChannel.setMessageHandler { _, reply in
                api.getOcrCapabilities { result in
                    switch result {
                    case let .success(res):
                        reply(wrapResult(res))
                    case let .failure(error):
                        reply(wrapError(error))
                    }
                }
            }
        } else {
            getOcrCapabilitiesChannel.setMessageHandler(nil)
        }
    }
}
