// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
    import Flutter
#elseif os(macOS)
    import FlutterMacOS
#else
    #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
    let code: String
    let message: String?
    let details: Sendable?

    init(code: String, message: String?, details: Sendable?) {
        self.code = code
        self.message = message
        self.details = details
    }

    var localizedDescription: String {
        return
            "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
    }
}

private func wrapResult(_ result: Any?) -> [Any?] {
    return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
    if let pigeonError = error as? PigeonError {
        return [
            pigeonError.code,
            pigeonError.message,
            pigeonError.details,
        ]
    }
    if let flutterError = error as? FlutterError {
        return [
            flutterError.code,
            flutterError.message,
            flutterError.details,
        ]
    }
    return [
        "\(error)",
        "\(Swift.type(of: error))",
        "Stacktrace: \(Thread.callStackSymbols)",
    ]
}

enum MessagesPigeonInternal {
    static func isNullish(_ value: Any?) -> Bool {
        guard let innerValue = value else {
            return true
        }

        if case Optional<Any>.some(Any?.none) = value {
            return true
        }

        return innerValue is NSNull
    }

    static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
        return (lhs.isNaN && rhs.isNaN) || lhs == rhs
    }

    static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
        if value.isNaN {
            hasher.combine(0x7FF8_0000_0000_0000)
        } else {
            // Normalize -0.0 to 0.0
            hasher.combine(value == 0 ? 0 : value)
        }
    }

    static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
        let cleanLhs = nilOrValue(lhs) as Any?
        let cleanRhs = nilOrValue(rhs) as Any?
        switch (cleanLhs, cleanRhs) {
        case (nil, nil):
            return true

        case (nil, _), (_, nil):
            return false

        case let (lhs as AnyObject, rhs as AnyObject) where lhs === rhs:
            return true

        case is (Void, Void):
            return true

        case let (lhsArray, rhsArray) as ([Double], [Double]):
            guard lhsArray.count == rhsArray.count else { return false }
            for (index, element) in lhsArray.enumerated() {
                if !doubleEquals(element, rhsArray[index]) {
                    return false
                }
            }
            return true

        case let (lhsArray, rhsArray) as ([Any?], [Any?]):
            guard lhsArray.count == rhsArray.count else { return false }
            for (index, element) in lhsArray.enumerated() {
                if !deepEquals(element, rhsArray[index]) {
                    return false
                }
            }
            return true

        case let (lhsDictionary, rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
            guard lhsDictionary.count == rhsDictionary.count else { return false }
            for (lhsKey, lhsValue) in lhsDictionary {
                var found = false
                for (rhsKey, rhsValue) in rhsDictionary {
                    if deepEquals(lhsKey, rhsKey) {
                        if deepEquals(lhsValue, rhsValue) {
                            found = true
                            break
                        } else {
                            return false
                        }
                    }
                }
                if !found { return false }
            }
            return true

        case let (lhs as Double, rhs as Double):
            return doubleEquals(lhs, rhs)

        case let (lhsHashable, rhsHashable) as (AnyHashable, AnyHashable):
            return lhsHashable == rhsHashable

        default:
            return false
        }
    }

    static func deepHash(value: Any?, hasher: inout Hasher) {
        let cleanValue = nilOrValue(value) as Any?
        if let cleanValue = cleanValue {
            if let doubleValue = cleanValue as? Double {
                doubleHash(doubleValue, &hasher)
            } else if let valueList = cleanValue as? [Any?] {
                for item in valueList {
                    deepHash(value: item, hasher: &hasher)
                }
            } else if let valueList = cleanValue as? [Double] {
                for item in valueList {
                    doubleHash(item, &hasher)
                }
            } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
                var result = 0
                for (key, value) in valueDict {
                    var entryKeyHasher = Hasher()
                    deepHash(value: key, hasher: &entryKeyHasher)
                    var entryValueHasher = Hasher()
                    deepHash(value: value, hasher: &entryValueHasher)
                    result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
                }
                hasher.combine(result)
            } else if let hashableValue = cleanValue as? AnyHashable {
                hasher.combine(hashableValue)
            } else {
                hasher.combine(String(describing: cleanValue))
            }
        } else {
            hasher.combine(0)
        }
    }
}

private func nilOrValue<T>(_ value: Any?) -> T? {
    if value is NSNull { return nil }
    return value as! T?
}

enum ScanSourceWire: Int, CaseIterable {
    case camera = 0
    case gallery = 1
}

enum ImageOriginWire: Int, CaseIterable {
    case camera = 0
    case screenshot = 1
    case download = 2
    case unknown = 3
}

enum ScanStatusWire: Int, CaseIterable {
    case success = 0
    case cancelled = 1
    case rejected = 2
}

/// Whether an OCR script model can run now or needs a download.
///
/// Declared after the shipped wire classes on purpose — Pigeon assigns codec
/// bytes in declaration order.
enum OcrModelStatusWire: Int, CaseIterable {
    case ready = 0
    case downloadRequired = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanOptionsWire: Hashable, CustomStringConvertible {
    var source: ScanSourceWire? = nil
    var maxPages: Int64? = nil
    var quality: Double? = nil
    var includeExif: Bool? = nil
    var includeGpsExif: Bool? = nil
    var ocr: Bool? = nil
    var cropAutoConfirm: Bool? = nil
    var autoRotate: Bool? = nil
    var includeRawExif: Bool? = nil
    var minimumTextHeight: Double? = nil
    var ocrGeometry: Bool? = nil
    /// Ordered BCP 47 language hints for on-device OCR. The app-facing package
    /// always forwards a resolved list, so the native boundary is deterministic.
    var ocrLanguages: [String]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ScanOptionsWire? {
        let source: ScanSourceWire? = nilOrValue(pigeonVar_list[0])
        let maxPages: Int64? = nilOrValue(pigeonVar_list[1])
        let quality: Double? = nilOrValue(pigeonVar_list[2])
        let includeExif: Bool? = nilOrValue(pigeonVar_list[3])
        let includeGpsExif: Bool? = nilOrValue(pigeonVar_list[4])
        let ocr: Bool? = nilOrValue(pigeonVar_list[5])
        let cropAutoConfirm: Bool? = nilOrValue(pigeonVar_list[6])
        let autoRotate: Bool? = nilOrValue(pigeonVar_list[7])
        let includeRawExif: Bool? = nilOrValue(pigeonVar_list[8])
        let minimumTextHeight: Double? = nilOrValue(pigeonVar_list[9])
        let ocrGeometry: Bool? = nilOrValue(pigeonVar_list[10])
        let ocrLanguages: [String]? = nilOrValue(pigeonVar_list[11])

        return ScanOptionsWire(
            source: source,
            maxPages: maxPages,
            quality: quality,
            includeExif: includeExif,
            includeGpsExif: includeGpsExif,
            ocr: ocr,
            cropAutoConfirm: cropAutoConfirm,
            autoRotate: autoRotate,
            includeRawExif: includeRawExif,
            minimumTextHeight: minimumTextHeight,
            ocrGeometry: ocrGeometry,
            ocrLanguages: ocrLanguages
        )
    }

    func toList() -> [Any?] {
        return [
            source,
            maxPages,
            quality,
            includeExif,
            includeGpsExif,
            ocr,
            cropAutoConfirm,
            autoRotate,
            includeRawExif,
            minimumTextHeight,
            ocrGeometry,
            ocrLanguages,
        ]
    }

    static func == (lhs: ScanOptionsWire, rhs: ScanOptionsWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.source, rhs.source) && MessagesPigeonInternal.deepEquals(lhs.maxPages, rhs.maxPages) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality) && MessagesPigeonInternal.deepEquals(lhs.includeExif, rhs.includeExif) && MessagesPigeonInternal.deepEquals(lhs.includeGpsExif, rhs.includeGpsExif) && MessagesPigeonInternal.deepEquals(lhs.ocr, rhs.ocr) && MessagesPigeonInternal.deepEquals(lhs.cropAutoConfirm, rhs.cropAutoConfirm) && MessagesPigeonInternal.deepEquals(lhs.autoRotate, rhs.autoRotate) && MessagesPigeonInternal.deepEquals(lhs.includeRawExif, rhs.includeRawExif) && MessagesPigeonInternal.deepEquals(lhs.minimumTextHeight, rhs.minimumTextHeight) && MessagesPigeonInternal.deepEquals(lhs.ocrGeometry, rhs.ocrGeometry) && MessagesPigeonInternal.deepEquals(lhs.ocrLanguages, rhs.ocrLanguages)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("ScanOptionsWire")
        MessagesPigeonInternal.deepHash(value: source, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: maxPages, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: includeExif, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: includeGpsExif, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocr, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: cropAutoConfirm, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: autoRotate, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: includeRawExif, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: minimumTextHeight, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocrGeometry, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocrLanguages, hasher: &hasher)
    }

    var description: String {
        return "ScanOptionsWire(source: \(String(describing: source)), maxPages: \(String(describing: maxPages)), quality: \(String(describing: quality)), includeExif: \(String(describing: includeExif)), includeGpsExif: \(String(describing: includeGpsExif)), ocr: \(String(describing: ocr)), cropAutoConfirm: \(String(describing: cropAutoConfirm)), autoRotate: \(String(describing: autoRotate)), includeRawExif: \(String(describing: includeRawExif)), minimumTextHeight: \(String(describing: minimumTextHeight)), ocrGeometry: \(String(describing: ocrGeometry)), ocrLanguages: \(String(describing: ocrLanguages)))"
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GpsDataWire: Hashable, CustomStringConvertible {
    var latitude: Double? = nil
    var longitude: Double? = nil
    var altitude: Double? = nil
    var timestamp: String? = nil
    var speed: Double? = nil
    var heading: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> GpsDataWire? {
        let latitude: Double? = nilOrValue(pigeonVar_list[0])
        let longitude: Double? = nilOrValue(pigeonVar_list[1])
        let altitude: Double? = nilOrValue(pigeonVar_list[2])
        let timestamp: String? = nilOrValue(pigeonVar_list[3])
        let speed: Double? = nilOrValue(pigeonVar_list[4])
        let heading: Double? = nilOrValue(pigeonVar_list[5])

        return GpsDataWire(
            latitude: latitude,
            longitude: longitude,
            altitude: altitude,
            timestamp: timestamp,
            speed: speed,
            heading: heading
        )
    }

    func toList() -> [Any?] {
        return [
            latitude,
            longitude,
            altitude,
            timestamp,
            speed,
            heading,
        ]
    }

    static func == (lhs: GpsDataWire, rhs: GpsDataWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.latitude, rhs.latitude) && MessagesPigeonInternal.deepEquals(lhs.longitude, rhs.longitude) && MessagesPigeonInternal.deepEquals(lhs.altitude, rhs.altitude) && MessagesPigeonInternal.deepEquals(lhs.timestamp, rhs.timestamp) && MessagesPigeonInternal.deepEquals(lhs.speed, rhs.speed) && MessagesPigeonInternal.deepEquals(lhs.heading, rhs.heading)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("GpsDataWire")
        MessagesPigeonInternal.deepHash(value: latitude, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: longitude, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: altitude, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: timestamp, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: speed, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: heading, hasher: &hasher)
    }

    var description: String {
        return "GpsDataWire(latitude: \(String(describing: latitude)), longitude: \(String(describing: longitude)), altitude: \(String(describing: altitude)), timestamp: \(String(describing: timestamp)), speed: \(String(describing: speed)), heading: \(String(describing: heading)))"
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiptExifWire: Hashable, CustomStringConvertible {
    var orientation: Int64? = nil
    var colorSpace: Int64? = nil
    var lightSource: Int64? = nil
    var exifVersion: String? = nil
    var make: String? = nil
    var model: String? = nil
    var software: String? = nil
    var dateTime: String? = nil
    var dateTimeOriginal: String? = nil
    var dateTimeDigitized: String? = nil
    var exposureTime: Double? = nil
    var fNumber: Double? = nil
    var iso: Double? = nil
    var focalLength: Double? = nil
    var flash: Int64? = nil
    var whiteBalance: Int64? = nil
    var exposureMode: Int64? = nil
    var exposureProgram: Int64? = nil
    var meteringMode: Int64? = nil
    var gps: GpsDataWire? = nil
    var raw: [String: Any?]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ReceiptExifWire? {
        let orientation: Int64? = nilOrValue(pigeonVar_list[0])
        let colorSpace: Int64? = nilOrValue(pigeonVar_list[1])
        let lightSource: Int64? = nilOrValue(pigeonVar_list[2])
        let exifVersion: String? = nilOrValue(pigeonVar_list[3])
        let make: String? = nilOrValue(pigeonVar_list[4])
        let model: String? = nilOrValue(pigeonVar_list[5])
        let software: String? = nilOrValue(pigeonVar_list[6])
        let dateTime: String? = nilOrValue(pigeonVar_list[7])
        let dateTimeOriginal: String? = nilOrValue(pigeonVar_list[8])
        let dateTimeDigitized: String? = nilOrValue(pigeonVar_list[9])
        let exposureTime: Double? = nilOrValue(pigeonVar_list[10])
        let fNumber: Double? = nilOrValue(pigeonVar_list[11])
        let iso: Double? = nilOrValue(pigeonVar_list[12])
        let focalLength: Double? = nilOrValue(pigeonVar_list[13])
        let flash: Int64? = nilOrValue(pigeonVar_list[14])
        let whiteBalance: Int64? = nilOrValue(pigeonVar_list[15])
        let exposureMode: Int64? = nilOrValue(pigeonVar_list[16])
        let exposureProgram: Int64? = nilOrValue(pigeonVar_list[17])
        let meteringMode: Int64? = nilOrValue(pigeonVar_list[18])
        let gps: GpsDataWire? = nilOrValue(pigeonVar_list[19])
        let raw: [String: Any?]? = nilOrValue(pigeonVar_list[20])

        return ReceiptExifWire(
            orientation: orientation,
            colorSpace: colorSpace,
            lightSource: lightSource,
            exifVersion: exifVersion,
            make: make,
            model: model,
            software: software,
            dateTime: dateTime,
            dateTimeOriginal: dateTimeOriginal,
            dateTimeDigitized: dateTimeDigitized,
            exposureTime: exposureTime,
            fNumber: fNumber,
            iso: iso,
            focalLength: focalLength,
            flash: flash,
            whiteBalance: whiteBalance,
            exposureMode: exposureMode,
            exposureProgram: exposureProgram,
            meteringMode: meteringMode,
            gps: gps,
            raw: raw
        )
    }

    func toList() -> [Any?] {
        return [
            orientation,
            colorSpace,
            lightSource,
            exifVersion,
            make,
            model,
            software,
            dateTime,
            dateTimeOriginal,
            dateTimeDigitized,
            exposureTime,
            fNumber,
            iso,
            focalLength,
            flash,
            whiteBalance,
            exposureMode,
            exposureProgram,
            meteringMode,
            gps,
            raw,
        ]
    }

    static func == (lhs: ReceiptExifWire, rhs: ReceiptExifWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.orientation, rhs.orientation) && MessagesPigeonInternal.deepEquals(lhs.colorSpace, rhs.colorSpace) && MessagesPigeonInternal.deepEquals(lhs.lightSource, rhs.lightSource) && MessagesPigeonInternal.deepEquals(lhs.exifVersion, rhs.exifVersion) && MessagesPigeonInternal.deepEquals(lhs.make, rhs.make) && MessagesPigeonInternal.deepEquals(lhs.model, rhs.model) && MessagesPigeonInternal.deepEquals(lhs.software, rhs.software) && MessagesPigeonInternal.deepEquals(lhs.dateTime, rhs.dateTime) && MessagesPigeonInternal.deepEquals(lhs.dateTimeOriginal, rhs.dateTimeOriginal) && MessagesPigeonInternal.deepEquals(lhs.dateTimeDigitized, rhs.dateTimeDigitized) && MessagesPigeonInternal.deepEquals(lhs.exposureTime, rhs.exposureTime) && MessagesPigeonInternal.deepEquals(lhs.fNumber, rhs.fNumber) && MessagesPigeonInternal.deepEquals(lhs.iso, rhs.iso) && MessagesPigeonInternal.deepEquals(lhs.focalLength, rhs.focalLength) && MessagesPigeonInternal.deepEquals(lhs.flash, rhs.flash) && MessagesPigeonInternal.deepEquals(lhs.whiteBalance, rhs.whiteBalance) && MessagesPigeonInternal.deepEquals(lhs.exposureMode, rhs.exposureMode) && MessagesPigeonInternal.deepEquals(lhs.exposureProgram, rhs.exposureProgram) && MessagesPigeonInternal.deepEquals(lhs.meteringMode, rhs.meteringMode) && MessagesPigeonInternal.deepEquals(lhs.gps, rhs.gps) && MessagesPigeonInternal.deepEquals(lhs.raw, rhs.raw)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("ReceiptExifWire")
        MessagesPigeonInternal.deepHash(value: orientation, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: colorSpace, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: lightSource, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: exifVersion, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: make, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: model, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: software, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: dateTime, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: dateTimeOriginal, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: dateTimeDigitized, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: exposureTime, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: fNumber, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: iso, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: focalLength, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: flash, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: whiteBalance, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: exposureMode, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: exposureProgram, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: meteringMode, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: gps, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: raw, hasher: &hasher)
    }

    var description: String {
        return "ReceiptExifWire(orientation: \(String(describing: orientation)), colorSpace: \(String(describing: colorSpace)), lightSource: \(String(describing: lightSource)), exifVersion: \(String(describing: exifVersion)), make: \(String(describing: make)), model: \(String(describing: model)), software: \(String(describing: software)), dateTime: \(String(describing: dateTime)), dateTimeOriginal: \(String(describing: dateTimeOriginal)), dateTimeDigitized: \(String(describing: dateTimeDigitized)), exposureTime: \(String(describing: exposureTime)), fNumber: \(String(describing: fNumber)), iso: \(String(describing: iso)), focalLength: \(String(describing: focalLength)), flash: \(String(describing: flash)), whiteBalance: \(String(describing: whiteBalance)), exposureMode: \(String(describing: exposureMode)), exposureProgram: \(String(describing: exposureProgram)), meteringMode: \(String(describing: meteringMode)), gps: \(String(describing: gps)), raw: \(String(describing: raw)))"
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct OcrQualityWire: Hashable, CustomStringConvertible {
    var textLength: Int64? = nil
    var lineCount: Int64? = nil
    var confidence: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrQualityWire? {
        let textLength: Int64? = nilOrValue(pigeonVar_list[0])
        let lineCount: Int64? = nilOrValue(pigeonVar_list[1])
        let confidence: Double? = nilOrValue(pigeonVar_list[2])

        return OcrQualityWire(
            textLength: textLength,
            lineCount: lineCount,
            confidence: confidence
        )
    }

    func toList() -> [Any?] {
        return [
            textLength,
            lineCount,
            confidence,
        ]
    }

    static func == (lhs: OcrQualityWire, rhs: OcrQualityWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.textLength, rhs.textLength) && MessagesPigeonInternal.deepEquals(lhs.lineCount, rhs.lineCount) && MessagesPigeonInternal.deepEquals(lhs.confidence, rhs.confidence)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("OcrQualityWire")
        MessagesPigeonInternal.deepHash(value: textLength, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: lineCount, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: confidence, hasher: &hasher)
    }

    var description: String {
        return "OcrQualityWire(textLength: \(String(describing: textLength)), lineCount: \(String(describing: lineCount)), confidence: \(String(describing: confidence)))"
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ReceiptImageWire: Hashable, CustomStringConvertible {
    var uri: String
    var width: Int64
    var height: Int64
    var fileName: String
    var mimeType: String
    var fileSize: Int64
    var imageOrigin: ImageOriginWire
    var ocrText: String? = nil
    var ocrQuality: OcrQualityWire? = nil
    var exif: ReceiptExifWire? = nil
    var ocrLines: [OcrLineWire]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ReceiptImageWire? {
        let uri = pigeonVar_list[0] as! String
        let width = pigeonVar_list[1] as! Int64
        let height = pigeonVar_list[2] as! Int64
        let fileName = pigeonVar_list[3] as! String
        let mimeType = pigeonVar_list[4] as! String
        let fileSize = pigeonVar_list[5] as! Int64
        let imageOrigin = pigeonVar_list[6] as! ImageOriginWire
        let ocrText: String? = nilOrValue(pigeonVar_list[7])
        let ocrQuality: OcrQualityWire? = nilOrValue(pigeonVar_list[8])
        let exif: ReceiptExifWire? = nilOrValue(pigeonVar_list[9])
        let ocrLines: [OcrLineWire]? = nilOrValue(pigeonVar_list[10])

        return ReceiptImageWire(
            uri: uri,
            width: width,
            height: height,
            fileName: fileName,
            mimeType: mimeType,
            fileSize: fileSize,
            imageOrigin: imageOrigin,
            ocrText: ocrText,
            ocrQuality: ocrQuality,
            exif: exif,
            ocrLines: ocrLines
        )
    }

    func toList() -> [Any?] {
        return [
            uri,
            width,
            height,
            fileName,
            mimeType,
            fileSize,
            imageOrigin,
            ocrText,
            ocrQuality,
            exif,
            ocrLines,
        ]
    }

    static func == (lhs: ReceiptImageWire, rhs: ReceiptImageWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.uri, rhs.uri) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.fileName, rhs.fileName) && MessagesPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && MessagesPigeonInternal.deepEquals(lhs.fileSize, rhs.fileSize) && MessagesPigeonInternal.deepEquals(lhs.imageOrigin, rhs.imageOrigin) && MessagesPigeonInternal.deepEquals(lhs.ocrText, rhs.ocrText) && MessagesPigeonInternal.deepEquals(lhs.ocrQuality, rhs.ocrQuality) && MessagesPigeonInternal.deepEquals(lhs.exif, rhs.exif) && MessagesPigeonInternal.deepEquals(lhs.ocrLines, rhs.ocrLines)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("ReceiptImageWire")
        MessagesPigeonInternal.deepHash(value: uri, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: fileName, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: fileSize, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: imageOrigin, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocrText, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocrQuality, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: exif, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: ocrLines, hasher: &hasher)
    }

    var description: String {
        return "ReceiptImageWire(uri: \(String(describing: uri)), width: \(String(describing: width)), height: \(String(describing: height)), fileName: \(String(describing: fileName)), mimeType: \(String(describing: mimeType)), fileSize: \(String(describing: fileSize)), imageOrigin: \(String(describing: imageOrigin)), ocrText: \(String(describing: ocrText)), ocrQuality: \(String(describing: ocrQuality)), exif: \(String(describing: exif)), ocrLines: \(String(describing: ocrLines)))"
    }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ScanResultWire: Hashable, CustomStringConvertible {
    var status: ScanStatusWire
    var images: [ReceiptImageWire]
    var rejectedImages: [ReceiptImageWire]
    /// Natively captured pages dropped before processing (absent means zero).
    /// iOS can exceed `maxPages` because VisionKit cannot enforce a page limit
    /// in its UI; declared last to keep existing wire positions stable.
    var discardedPageCount: Int64? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> ScanResultWire? {
        let status = pigeonVar_list[0] as! ScanStatusWire
        let images = pigeonVar_list[1] as! [ReceiptImageWire]
        let rejectedImages = pigeonVar_list[2] as! [ReceiptImageWire]
        let discardedPageCount: Int64? = nilOrValue(pigeonVar_list[3])

        return ScanResultWire(
            status: status,
            images: images,
            rejectedImages: rejectedImages,
            discardedPageCount: discardedPageCount
        )
    }

    func toList() -> [Any?] {
        return [
            status,
            images,
            rejectedImages,
            discardedPageCount,
        ]
    }

    static func == (lhs: ScanResultWire, rhs: ScanResultWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.status, rhs.status) && MessagesPigeonInternal.deepEquals(lhs.images, rhs.images) && MessagesPigeonInternal.deepEquals(lhs.rejectedImages, rhs.rejectedImages) && MessagesPigeonInternal.deepEquals(lhs.discardedPageCount, rhs.discardedPageCount)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("ScanResultWire")
        MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: images, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: rejectedImages, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: discardedPageCount, hasher: &hasher)
    }

    var description: String {
        return "ScanResultWire(status: \(String(describing: status)), images: \(String(describing: images)), rejectedImages: \(String(describing: rejectedImages)), discardedPageCount: \(String(describing: discardedPageCount)))"
    }
}

/// One recognized text line's box, in top-left-origin pixels of the output image.
///
/// Declared after [ScanResultWire] on purpose: Pigeon assigns codec bytes in
/// declaration order, so new wire classes are appended at the end to keep the
/// byte assignments of already-shipped types stable.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrLineWire: Hashable, CustomStringConvertible {
    var text: String
    var x: Int64
    var y: Int64
    var width: Int64
    var height: Int64
    var confidence: Double? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrLineWire? {
        let text = pigeonVar_list[0] as! String
        let x = pigeonVar_list[1] as! Int64
        let y = pigeonVar_list[2] as! Int64
        let width = pigeonVar_list[3] as! Int64
        let height = pigeonVar_list[4] as! Int64
        let confidence: Double? = nilOrValue(pigeonVar_list[5])

        return OcrLineWire(
            text: text,
            x: x,
            y: y,
            width: width,
            height: height,
            confidence: confidence
        )
    }

    func toList() -> [Any?] {
        return [
            text,
            x,
            y,
            width,
            height,
            confidence,
        ]
    }

    static func == (lhs: OcrLineWire, rhs: OcrLineWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.x, rhs.x) && MessagesPigeonInternal.deepEquals(lhs.y, rhs.y) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.confidence, rhs.confidence)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("OcrLineWire")
        MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: x, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: y, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: confidence, hasher: &hasher)
    }

    var description: String {
        return "OcrLineWire(text: \(String(describing: text)), x: \(String(describing: x)), y: \(String(describing: y)), width: \(String(describing: width)), height: \(String(describing: height)), confidence: \(String(describing: confidence)))"
    }
}

/// One script family's readiness, reported by Android.
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrModelStateWire: Hashable, CustomStringConvertible {
    /// Unicode script identifier such as `Latn`, `Kore`, `Jpan`, `Hans`, `Hant`,
    /// or `Deva`.
    var script: String
    var status: OcrModelStatusWire

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrModelStateWire? {
        let script = pigeonVar_list[0] as! String
        let status = pigeonVar_list[1] as! OcrModelStatusWire

        return OcrModelStateWire(
            script: script,
            status: status
        )
    }

    func toList() -> [Any?] {
        return [
            script,
            status,
        ]
    }

    static func == (lhs: OcrModelStateWire, rhs: OcrModelStateWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.script, rhs.script) && MessagesPigeonInternal.deepEquals(lhs.status, rhs.status)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("OcrModelStateWire")
        MessagesPigeonInternal.deepHash(value: script, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: status, hasher: &hasher)
    }

    var description: String {
        return "OcrModelStateWire(script: \(String(describing: script)), status: \(String(describing: status)))"
    }
}

/// Native OCR capability. `supportedLanguages` is iOS-only (Vision reports
/// exact identifiers); `models` is Android-only (ML Kit script families).
///
/// Generated class from Pigeon that represents data sent in messages.
struct OcrCapabilitiesWire: Hashable, CustomStringConvertible {
    var supportedLanguages: [String]? = nil
    var models: [OcrModelStateWire]? = nil

    // swift-format-ignore: AlwaysUseLowerCamelCase
    static func fromList(_ pigeonVar_list: [Any?]) -> OcrCapabilitiesWire? {
        let supportedLanguages: [String]? = nilOrValue(pigeonVar_list[0])
        let models: [OcrModelStateWire]? = nilOrValue(pigeonVar_list[1])

        return OcrCapabilitiesWire(
            supportedLanguages: supportedLanguages,
            models: models
        )
    }

    func toList() -> [Any?] {
        return [
            supportedLanguages,
            models,
        ]
    }

    static func == (lhs: OcrCapabilitiesWire, rhs: OcrCapabilitiesWire) -> Bool {
        if Swift.type(of: lhs) != Swift.type(of: rhs) {
            return false
        }
        return MessagesPigeonInternal.deepEquals(lhs.supportedLanguages, rhs.supportedLanguages) && MessagesPigeonInternal.deepEquals(lhs.models, rhs.models)
    }

    func hash(into hasher: inout Hasher) {
        hasher.combine("OcrCapabilitiesWire")
        MessagesPigeonInternal.deepHash(value: supportedLanguages, hasher: &hasher)
        MessagesPigeonInternal.deepHash(value: models, hasher: &hasher)
    }

    var description: String {
        return "OcrCapabilitiesWire(supportedLanguages: \(String(describing: supportedLanguages)), models: \(String(describing: models)))"
    }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
    override func readValue(ofType type: UInt8) -> Any? {
        switch type {
        case 129:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ScanSourceWire(rawValue: enumResultAsInt)
            }
            return nil
        case 130:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ImageOriginWire(rawValue: enumResultAsInt)
            }
            return nil
        case 131:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return ScanStatusWire(rawValue: enumResultAsInt)
            }
            return nil
        case 132:
            let enumResultAsInt: Int? = nilOrValue(readValue() as! Int?)
            if let enumResultAsInt = enumResultAsInt {
                return OcrModelStatusWire(rawValue: enumResultAsInt)
            }
            return nil
        case 133:
            return ScanOptionsWire.fromList(readValue() as! [Any?])
        case 134:
            return GpsDataWire.fromList(readValue() as! [Any?])
        case 135:
            return ReceiptExifWire.fromList(readValue() as! [Any?])
        case 136:
            return OcrQualityWire.fromList(readValue() as! [Any?])
        case 137:
            return ReceiptImageWire.fromList(readValue() as! [Any?])
        case 138:
            return ScanResultWire.fromList(readValue() as! [Any?])
        case 139:
            return OcrLineWire.fromList(readValue() as! [Any?])
        case 140:
            return OcrModelStateWire.fromList(readValue() as! [Any?])
        case 141:
            return OcrCapabilitiesWire.fromList(readValue() as! [Any?])
        default:
            return super.readValue(ofType: type)
        }
    }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
    override func writeValue(_ value: Any) {
        if let value = value as? ScanSourceWire {
            super.writeByte(129)
            super.writeValue(value.rawValue)
        } else if let value = value as? ImageOriginWire {
            super.writeByte(130)
            super.writeValue(value.rawValue)
        } else if let value = value as? ScanStatusWire {
            super.writeByte(131)
            super.writeValue(value.rawValue)
        } else if let value = value as? OcrModelStatusWire {
            super.writeByte(132)
            super.writeValue(value.rawValue)
        } else if let value = value as? ScanOptionsWire {
            super.writeByte(133)
            super.writeValue(value.toList())
        } else if let value = value as? GpsDataWire {
            super.writeByte(134)
            super.writeValue(value.toList())
        } else if let value = value as? ReceiptExifWire {
            super.writeByte(135)
            super.writeValue(value.toList())
        } else if let value = value as? OcrQualityWire {
            super.writeByte(136)
            super.writeValue(value.toList())
        } else if let value = value as? ReceiptImageWire {
            super.writeByte(137)
            super.writeValue(value.toList())
        } else if let value = value as? ScanResultWire {
            super.writeByte(138)
            super.writeValue(value.toList())
        } else if let value = value as? OcrLineWire {
            super.writeByte(139)
            super.writeValue(value.toList())
        } else if let value = value as? OcrModelStateWire {
            super.writeByte(140)
            super.writeValue(value.toList())
        } else if let value = value as? OcrCapabilitiesWire {
            super.writeByte(141)
            super.writeValue(value.toList())
        } else {
            super.writeValue(value)
        }
    }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
    override func reader(with data: Data) -> FlutterStandardReader {
        return MessagesPigeonCodecReader(data: data)
    }

    override func writer(with data: NSMutableData) -> FlutterStandardWriter {
        return MessagesPigeonCodecWriter(data: data)
    }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
    static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ReceiptScannerApi {
    func scan(options: ScanOptionsWire) async throws -> ScanResultWire
    /// Reports current OCR capability. Must not download a model or open UI.
    func getOcrCapabilities() async throws -> OcrCapabilitiesWire
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ReceiptScannerApiSetup {
    static var codec: FlutterStandardMessageCodec {
        MessagesPigeonCodec.shared
    }

    /// Sets up an instance of `ReceiptScannerApi` to handle messages through the `binaryMessenger`.
    static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ReceiptScannerApi?, messageChannelSuffix: String = "") {
        let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
        let scanChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.scan\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            scanChannel.setMessageHandler { message, reply in
                let args = message as! [Any?]
                let optionsArg = args[0] as! ScanOptionsWire
                Task { @MainActor in
                    do {
                        let result = try await api.scan(options: optionsArg)
                        reply(wrapResult(result))
                    } catch {
                        reply(wrapError(error))
                    }
                }
            }
        } else {
            scanChannel.setMessageHandler(nil)
        }
        // Reports current OCR capability. Must not download a model or open UI.
        let getOcrCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.getOcrCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
        if let api = api {
            getOcrCapabilitiesChannel.setMessageHandler { _, reply in
                Task { @MainActor in
                    do {
                        let result = try await api.getOcrCapabilities()
                        reply(wrapResult(result))
                    } catch {
                        reply(wrapError(error))
                    }
                }
            }
        } else {
            getOcrCapabilitiesChannel.setMessageHandler(nil)
        }
    }
}
