// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

enum ScanSource {
  camera,
  gallery,
}

enum ImageOrigin {
  camera,
  screenshot,
  download,
  unknown,
}

enum ScanStatus {
  success,
  cancelled,
  rejected,
}

class OcrFloorMessage {
  OcrFloorMessage({
    this.minTextLength,
    this.minLines,
    this.minConfidence,
  });

  int? minTextLength;

  int? minLines;

  double? minConfidence;

  Object encode() {
    return <Object?>[
      minTextLength,
      minLines,
      minConfidence,
    ];
  }

  static OcrFloorMessage decode(Object result) {
    result as List<Object?>;
    return OcrFloorMessage(
      minTextLength: result[0] as int?,
      minLines: result[1] as int?,
      minConfidence: result[2] as double?,
    );
  }
}

class ScanOptions {
  ScanOptions({
    this.source,
    this.maxPages,
    this.quality,
    this.includeExif,
    this.includeGpsExif,
    this.ocr,
    this.cropAutoConfirm,
    this.autoRotate,
    this.includeRawExif,
    this.minimumTextHeight,
  });

  ScanSource? source;

  int? maxPages;

  double? quality;

  bool? includeExif;

  bool? includeGpsExif;

  bool? ocr;

  bool? cropAutoConfirm;

  bool? autoRotate;

  bool? includeRawExif;

  double? minimumTextHeight;

  Object encode() {
    return <Object?>[
      source,
      maxPages,
      quality,
      includeExif,
      includeGpsExif,
      ocr,
      cropAutoConfirm,
      autoRotate,
      includeRawExif,
      minimumTextHeight,
    ];
  }

  static ScanOptions decode(Object result) {
    result as List<Object?>;
    return ScanOptions(
      source: result[0] as ScanSource?,
      maxPages: result[1] as int?,
      quality: result[2] as double?,
      includeExif: result[3] as bool?,
      includeGpsExif: result[4] as bool?,
      ocr: result[5] as bool?,
      cropAutoConfirm: result[6] as bool?,
      autoRotate: result[7] as bool?,
      includeRawExif: result[8] as bool?,
      minimumTextHeight: result[9] as double?,
    );
  }
}

class GpsData {
  GpsData({
    this.latitude,
    this.longitude,
    this.altitude,
    this.timestamp,
    this.speed,
    this.heading,
  });

  double? latitude;

  double? longitude;

  double? altitude;

  String? timestamp;

  double? speed;

  double? heading;

  Object encode() {
    return <Object?>[
      latitude,
      longitude,
      altitude,
      timestamp,
      speed,
      heading,
    ];
  }

  static GpsData decode(Object result) {
    result as List<Object?>;
    return GpsData(
      latitude: result[0] as double?,
      longitude: result[1] as double?,
      altitude: result[2] as double?,
      timestamp: result[3] as String?,
      speed: result[4] as double?,
      heading: result[5] as double?,
    );
  }
}

class ReceiptExif {
  ReceiptExif({
    this.orientation,
    this.colorSpace,
    this.lightSource,
    this.exifVersion,
    this.make,
    this.model,
    this.software,
    this.dateTime,
    this.dateTimeOriginal,
    this.dateTimeDigitized,
    this.exposureTime,
    this.fNumber,
    this.iso,
    this.focalLength,
    this.flash,
    this.whiteBalance,
    this.exposureMode,
    this.exposureProgram,
    this.meteringMode,
    this.gps,
    this.raw,
  });

  int? orientation;

  int? colorSpace;

  int? lightSource;

  String? exifVersion;

  String? make;

  String? model;

  String? software;

  String? dateTime;

  String? dateTimeOriginal;

  String? dateTimeDigitized;

  double? exposureTime;

  double? fNumber;

  double? iso;

  double? focalLength;

  int? flash;

  int? whiteBalance;

  int? exposureMode;

  int? exposureProgram;

  int? meteringMode;

  GpsData? gps;

  Map<String, Object?>? raw;

  Object encode() {
    return <Object?>[
      orientation,
      colorSpace,
      lightSource,
      exifVersion,
      make,
      model,
      software,
      dateTime,
      dateTimeOriginal,
      dateTimeDigitized,
      exposureTime,
      fNumber,
      iso,
      focalLength,
      flash,
      whiteBalance,
      exposureMode,
      exposureProgram,
      meteringMode,
      gps,
      raw,
    ];
  }

  static ReceiptExif decode(Object result) {
    result as List<Object?>;
    return ReceiptExif(
      orientation: result[0] as int?,
      colorSpace: result[1] as int?,
      lightSource: result[2] as int?,
      exifVersion: result[3] as String?,
      make: result[4] as String?,
      model: result[5] as String?,
      software: result[6] as String?,
      dateTime: result[7] as String?,
      dateTimeOriginal: result[8] as String?,
      dateTimeDigitized: result[9] as String?,
      exposureTime: result[10] as double?,
      fNumber: result[11] as double?,
      iso: result[12] as double?,
      focalLength: result[13] as double?,
      flash: result[14] as int?,
      whiteBalance: result[15] as int?,
      exposureMode: result[16] as int?,
      exposureProgram: result[17] as int?,
      meteringMode: result[18] as int?,
      gps: result[19] as GpsData?,
      raw: (result[20] as Map<Object?, Object?>?)?.cast<String, Object?>(),
    );
  }
}

class OcrQuality {
  OcrQuality({
    this.textLength,
    this.lineCount,
    this.confidence,
  });

  int? textLength;

  int? lineCount;

  double? confidence;

  Object encode() {
    return <Object?>[
      textLength,
      lineCount,
      confidence,
    ];
  }

  static OcrQuality decode(Object result) {
    result as List<Object?>;
    return OcrQuality(
      textLength: result[0] as int?,
      lineCount: result[1] as int?,
      confidence: result[2] as double?,
    );
  }
}

class ReceiptImage {
  ReceiptImage({
    required this.uri,
    required this.width,
    required this.height,
    required this.fileName,
    required this.mimeType,
    required this.fileSize,
    required this.imageOrigin,
    this.ocrText,
    this.ocrQuality,
    this.exif,
  });

  String uri;

  int width;

  int height;

  String fileName;

  String mimeType;

  int fileSize;

  ImageOrigin imageOrigin;

  String? ocrText;

  OcrQuality? ocrQuality;

  ReceiptExif? exif;

  Object encode() {
    return <Object?>[
      uri,
      width,
      height,
      fileName,
      mimeType,
      fileSize,
      imageOrigin,
      ocrText,
      ocrQuality,
      exif,
    ];
  }

  static ReceiptImage decode(Object result) {
    result as List<Object?>;
    return ReceiptImage(
      uri: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      fileName: result[3]! as String,
      mimeType: result[4]! as String,
      fileSize: result[5]! as int,
      imageOrigin: result[6]! as ImageOrigin,
      ocrText: result[7] as String?,
      ocrQuality: result[8] as OcrQuality?,
      exif: result[9] as ReceiptExif?,
    );
  }
}

class ScanResult {
  ScanResult({
    required this.status,
    required this.images,
    required this.rejectedImages,
  });

  ScanStatus status;

  List<ReceiptImage> images;

  List<ReceiptImage> rejectedImages;

  Object encode() {
    return <Object?>[
      status,
      images,
      rejectedImages,
    ];
  }

  static ScanResult decode(Object result) {
    result as List<Object?>;
    return ScanResult(
      status: result[0]! as ScanStatus,
      images: (result[1] as List<Object?>?)!.cast<ReceiptImage>(),
      rejectedImages: (result[2] as List<Object?>?)!.cast<ReceiptImage>(),
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ScanSource) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ImageOrigin) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ScanStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is OcrFloorMessage) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is ScanOptions) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is GpsData) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ReceiptExif) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is OcrQuality) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is ReceiptImage) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ScanResult) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ScanSource.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ImageOrigin.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : ScanStatus.values[value];
      case 132: 
        return OcrFloorMessage.decode(readValue(buffer)!);
      case 133: 
        return ScanOptions.decode(readValue(buffer)!);
      case 134: 
        return GpsData.decode(readValue(buffer)!);
      case 135: 
        return ReceiptExif.decode(readValue(buffer)!);
      case 136: 
        return OcrQuality.decode(readValue(buffer)!);
      case 137: 
        return ReceiptImage.decode(readValue(buffer)!);
      case 138: 
        return ScanResult.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ReceiptScannerApi {
  /// Constructor for [ReceiptScannerApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ReceiptScannerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<ScanResult> scan(ScanOptions options) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.flutter_receipt_scanner_platform_interface.ReceiptScannerApi.scan$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[options]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as ScanResult?)!;
    }
  }
}
