// Autogenerated from Pigeon (v29.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(List<Object?>? replyList, String channelName, {required bool isNullValid}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(code: replyList[0]! as String, message: replyList[1] as String?, details: replyList[2]);
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}

bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length && a.indexed.every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}

enum ScanSourceWire { camera, gallery }

enum ImageOriginWire { camera, screenshot, download, unknown }

enum ScanStatusWire { success, cancelled, rejected }

/// Whether an OCR script model can run now or needs a download.
///
/// Declared after the shipped wire classes on purpose — Pigeon assigns codec
/// bytes in declaration order.
enum OcrModelStatusWire { ready, downloadRequired }

class ScanOptionsWire {
  ScanOptionsWire({
    this.source,
    this.maxPages,
    this.quality,
    this.includeExif,
    this.includeGpsExif,
    this.ocr,
    this.cropAutoConfirm,
    this.autoRotate,
    this.includeRawExif,
    this.minimumTextHeight,
    this.ocrGeometry,
    this.ocrLanguages,
  });

  ScanSourceWire? source;

  int? maxPages;

  double? quality;

  bool? includeExif;

  bool? includeGpsExif;

  bool? ocr;

  bool? cropAutoConfirm;

  bool? autoRotate;

  bool? includeRawExif;

  double? minimumTextHeight;

  bool? ocrGeometry;

  /// Ordered BCP 47 language hints for on-device OCR. The app-facing package
  /// always forwards a resolved list, so the native boundary is deterministic.
  List<String>? ocrLanguages;

  List<Object?> _toList() {
    return <Object?>[
      source,
      maxPages,
      quality,
      includeExif,
      includeGpsExif,
      ocr,
      cropAutoConfirm,
      autoRotate,
      includeRawExif,
      minimumTextHeight,
      ocrGeometry,
      ocrLanguages,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ScanOptionsWire decode(Object result) {
    result as List<Object?>;
    return ScanOptionsWire(
      source: result[0] as ScanSourceWire?,
      maxPages: result[1] as int?,
      quality: result[2] as double?,
      includeExif: result[3] as bool?,
      includeGpsExif: result[4] as bool?,
      ocr: result[5] as bool?,
      cropAutoConfirm: result[6] as bool?,
      autoRotate: result[7] as bool?,
      includeRawExif: result[8] as bool?,
      minimumTextHeight: result[9] as double?,
      ocrGeometry: result[10] as bool?,
      ocrLanguages: (result[11] as List<Object?>?)?.cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanOptionsWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(source, other.source) &&
        _deepEquals(maxPages, other.maxPages) &&
        _deepEquals(quality, other.quality) &&
        _deepEquals(includeExif, other.includeExif) &&
        _deepEquals(includeGpsExif, other.includeGpsExif) &&
        _deepEquals(ocr, other.ocr) &&
        _deepEquals(cropAutoConfirm, other.cropAutoConfirm) &&
        _deepEquals(autoRotate, other.autoRotate) &&
        _deepEquals(includeRawExif, other.includeRawExif) &&
        _deepEquals(minimumTextHeight, other.minimumTextHeight) &&
        _deepEquals(ocrGeometry, other.ocrGeometry) &&
        _deepEquals(ocrLanguages, other.ocrLanguages);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScanOptionsWire(source: $source, maxPages: $maxPages, quality: $quality, includeExif: $includeExif, includeGpsExif: $includeGpsExif, ocr: $ocr, cropAutoConfirm: $cropAutoConfirm, autoRotate: $autoRotate, includeRawExif: $includeRawExif, minimumTextHeight: $minimumTextHeight, ocrGeometry: $ocrGeometry, ocrLanguages: $ocrLanguages)';
  }
}

class GpsDataWire {
  GpsDataWire({this.latitude, this.longitude, this.altitude, this.timestamp, this.speed, this.heading});

  double? latitude;

  double? longitude;

  double? altitude;

  String? timestamp;

  double? speed;

  double? heading;

  List<Object?> _toList() {
    return <Object?>[latitude, longitude, altitude, timestamp, speed, heading];
  }

  Object encode() {
    return _toList();
  }

  static GpsDataWire decode(Object result) {
    result as List<Object?>;
    return GpsDataWire(
      latitude: result[0] as double?,
      longitude: result[1] as double?,
      altitude: result[2] as double?,
      timestamp: result[3] as String?,
      speed: result[4] as double?,
      heading: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GpsDataWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(latitude, other.latitude) &&
        _deepEquals(longitude, other.longitude) &&
        _deepEquals(altitude, other.altitude) &&
        _deepEquals(timestamp, other.timestamp) &&
        _deepEquals(speed, other.speed) &&
        _deepEquals(heading, other.heading);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GpsDataWire(latitude: $latitude, longitude: $longitude, altitude: $altitude, timestamp: $timestamp, speed: $speed, heading: $heading)';
  }
}

class ReceiptExifWire {
  ReceiptExifWire({
    this.orientation,
    this.colorSpace,
    this.lightSource,
    this.exifVersion,
    this.make,
    this.model,
    this.software,
    this.dateTime,
    this.dateTimeOriginal,
    this.dateTimeDigitized,
    this.exposureTime,
    this.fNumber,
    this.iso,
    this.focalLength,
    this.flash,
    this.whiteBalance,
    this.exposureMode,
    this.exposureProgram,
    this.meteringMode,
    this.gps,
    this.raw,
  });

  int? orientation;

  int? colorSpace;

  int? lightSource;

  String? exifVersion;

  String? make;

  String? model;

  String? software;

  String? dateTime;

  String? dateTimeOriginal;

  String? dateTimeDigitized;

  double? exposureTime;

  double? fNumber;

  double? iso;

  double? focalLength;

  int? flash;

  int? whiteBalance;

  int? exposureMode;

  int? exposureProgram;

  int? meteringMode;

  GpsDataWire? gps;

  Map<String, Object?>? raw;

  List<Object?> _toList() {
    return <Object?>[
      orientation,
      colorSpace,
      lightSource,
      exifVersion,
      make,
      model,
      software,
      dateTime,
      dateTimeOriginal,
      dateTimeDigitized,
      exposureTime,
      fNumber,
      iso,
      focalLength,
      flash,
      whiteBalance,
      exposureMode,
      exposureProgram,
      meteringMode,
      gps,
      raw,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ReceiptExifWire decode(Object result) {
    result as List<Object?>;
    return ReceiptExifWire(
      orientation: result[0] as int?,
      colorSpace: result[1] as int?,
      lightSource: result[2] as int?,
      exifVersion: result[3] as String?,
      make: result[4] as String?,
      model: result[5] as String?,
      software: result[6] as String?,
      dateTime: result[7] as String?,
      dateTimeOriginal: result[8] as String?,
      dateTimeDigitized: result[9] as String?,
      exposureTime: result[10] as double?,
      fNumber: result[11] as double?,
      iso: result[12] as double?,
      focalLength: result[13] as double?,
      flash: result[14] as int?,
      whiteBalance: result[15] as int?,
      exposureMode: result[16] as int?,
      exposureProgram: result[17] as int?,
      meteringMode: result[18] as int?,
      gps: result[19] as GpsDataWire?,
      raw: (result[20] as Map<Object?, Object?>?)?.cast<String, Object?>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReceiptExifWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(orientation, other.orientation) &&
        _deepEquals(colorSpace, other.colorSpace) &&
        _deepEquals(lightSource, other.lightSource) &&
        _deepEquals(exifVersion, other.exifVersion) &&
        _deepEquals(make, other.make) &&
        _deepEquals(model, other.model) &&
        _deepEquals(software, other.software) &&
        _deepEquals(dateTime, other.dateTime) &&
        _deepEquals(dateTimeOriginal, other.dateTimeOriginal) &&
        _deepEquals(dateTimeDigitized, other.dateTimeDigitized) &&
        _deepEquals(exposureTime, other.exposureTime) &&
        _deepEquals(fNumber, other.fNumber) &&
        _deepEquals(iso, other.iso) &&
        _deepEquals(focalLength, other.focalLength) &&
        _deepEquals(flash, other.flash) &&
        _deepEquals(whiteBalance, other.whiteBalance) &&
        _deepEquals(exposureMode, other.exposureMode) &&
        _deepEquals(exposureProgram, other.exposureProgram) &&
        _deepEquals(meteringMode, other.meteringMode) &&
        _deepEquals(gps, other.gps) &&
        _deepEquals(raw, other.raw);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ReceiptExifWire(orientation: $orientation, colorSpace: $colorSpace, lightSource: $lightSource, exifVersion: $exifVersion, make: $make, model: $model, software: $software, dateTime: $dateTime, dateTimeOriginal: $dateTimeOriginal, dateTimeDigitized: $dateTimeDigitized, exposureTime: $exposureTime, fNumber: $fNumber, iso: $iso, focalLength: $focalLength, flash: $flash, whiteBalance: $whiteBalance, exposureMode: $exposureMode, exposureProgram: $exposureProgram, meteringMode: $meteringMode, gps: $gps, raw: $raw)';
  }
}

class OcrQualityWire {
  OcrQualityWire({this.textLength, this.lineCount, this.confidence});

  int? textLength;

  int? lineCount;

  double? confidence;

  List<Object?> _toList() {
    return <Object?>[textLength, lineCount, confidence];
  }

  Object encode() {
    return _toList();
  }

  static OcrQualityWire decode(Object result) {
    result as List<Object?>;
    return OcrQualityWire(
      textLength: result[0] as int?,
      lineCount: result[1] as int?,
      confidence: result[2] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrQualityWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(textLength, other.textLength) &&
        _deepEquals(lineCount, other.lineCount) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrQualityWire(textLength: $textLength, lineCount: $lineCount, confidence: $confidence)';
  }
}

class ReceiptImageWire {
  ReceiptImageWire({
    required this.uri,
    required this.width,
    required this.height,
    required this.fileName,
    required this.mimeType,
    required this.fileSize,
    required this.imageOrigin,
    this.ocrText,
    this.ocrQuality,
    this.exif,
    this.ocrLines,
  });

  String uri;

  int width;

  int height;

  String fileName;

  String mimeType;

  int fileSize;

  ImageOriginWire imageOrigin;

  String? ocrText;

  OcrQualityWire? ocrQuality;

  ReceiptExifWire? exif;

  List<OcrLineWire>? ocrLines;

  List<Object?> _toList() {
    return <Object?>[
      uri,
      width,
      height,
      fileName,
      mimeType,
      fileSize,
      imageOrigin,
      ocrText,
      ocrQuality,
      exif,
      ocrLines,
    ];
  }

  Object encode() {
    return _toList();
  }

  static ReceiptImageWire decode(Object result) {
    result as List<Object?>;
    return ReceiptImageWire(
      uri: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      fileName: result[3]! as String,
      mimeType: result[4]! as String,
      fileSize: result[5]! as int,
      imageOrigin: result[6]! as ImageOriginWire,
      ocrText: result[7] as String?,
      ocrQuality: result[8] as OcrQualityWire?,
      exif: result[9] as ReceiptExifWire?,
      ocrLines: (result[10] as List<Object?>?)?.cast<OcrLineWire>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ReceiptImageWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(uri, other.uri) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(fileName, other.fileName) &&
        _deepEquals(mimeType, other.mimeType) &&
        _deepEquals(fileSize, other.fileSize) &&
        _deepEquals(imageOrigin, other.imageOrigin) &&
        _deepEquals(ocrText, other.ocrText) &&
        _deepEquals(ocrQuality, other.ocrQuality) &&
        _deepEquals(exif, other.exif) &&
        _deepEquals(ocrLines, other.ocrLines);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ReceiptImageWire(uri: $uri, width: $width, height: $height, fileName: $fileName, mimeType: $mimeType, fileSize: $fileSize, imageOrigin: $imageOrigin, ocrText: $ocrText, ocrQuality: $ocrQuality, exif: $exif, ocrLines: $ocrLines)';
  }
}

class ScanResultWire {
  ScanResultWire({required this.status, required this.images, required this.rejectedImages, this.discardedPageCount});

  ScanStatusWire status;

  List<ReceiptImageWire> images;

  List<ReceiptImageWire> rejectedImages;

  /// Natively captured pages dropped before processing (absent means zero).
  /// iOS can exceed `maxPages` because VisionKit cannot enforce a page limit
  /// in its UI; declared last to keep existing wire positions stable.
  int? discardedPageCount;

  List<Object?> _toList() {
    return <Object?>[status, images, rejectedImages, discardedPageCount];
  }

  Object encode() {
    return _toList();
  }

  static ScanResultWire decode(Object result) {
    result as List<Object?>;
    return ScanResultWire(
      status: result[0]! as ScanStatusWire,
      images: (result[1]! as List<Object?>).cast<ReceiptImageWire>(),
      rejectedImages: (result[2]! as List<Object?>).cast<ReceiptImageWire>(),
      discardedPageCount: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ScanResultWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(status, other.status) &&
        _deepEquals(images, other.images) &&
        _deepEquals(rejectedImages, other.rejectedImages) &&
        _deepEquals(discardedPageCount, other.discardedPageCount);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ScanResultWire(status: $status, images: $images, rejectedImages: $rejectedImages, discardedPageCount: $discardedPageCount)';
  }
}

/// One recognized text line's box, in top-left-origin pixels of the output image.
///
/// Declared after [ScanResultWire] on purpose: Pigeon assigns codec bytes in
/// declaration order, so new wire classes are appended at the end to keep the
/// byte assignments of already-shipped types stable.
class OcrLineWire {
  OcrLineWire({
    required this.text,
    required this.x,
    required this.y,
    required this.width,
    required this.height,
    this.confidence,
  });

  String text;

  int x;

  int y;

  int width;

  int height;

  double? confidence;

  List<Object?> _toList() {
    return <Object?>[text, x, y, width, height, confidence];
  }

  Object encode() {
    return _toList();
  }

  static OcrLineWire decode(Object result) {
    result as List<Object?>;
    return OcrLineWire(
      text: result[0]! as String,
      x: result[1]! as int,
      y: result[2]! as int,
      width: result[3]! as int,
      height: result[4]! as int,
      confidence: result[5] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrLineWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(text, other.text) &&
        _deepEquals(x, other.x) &&
        _deepEquals(y, other.y) &&
        _deepEquals(width, other.width) &&
        _deepEquals(height, other.height) &&
        _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrLineWire(text: $text, x: $x, y: $y, width: $width, height: $height, confidence: $confidence)';
  }
}

/// One script family's readiness, reported by Android.
class OcrModelStateWire {
  OcrModelStateWire({required this.script, required this.status});

  /// Unicode script identifier such as `Latn`, `Kore`, `Jpan`, `Hans`, `Hant`,
  /// or `Deva`.
  String script;

  OcrModelStatusWire status;

  List<Object?> _toList() {
    return <Object?>[script, status];
  }

  Object encode() {
    return _toList();
  }

  static OcrModelStateWire decode(Object result) {
    result as List<Object?>;
    return OcrModelStateWire(script: result[0]! as String, status: result[1]! as OcrModelStatusWire);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrModelStateWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(script, other.script) && _deepEquals(status, other.status);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrModelStateWire(script: $script, status: $status)';
  }
}

/// Native OCR capability. `supportedLanguages` is iOS-only (Vision reports
/// exact identifiers); `models` is Android-only (ML Kit script families).
class OcrCapabilitiesWire {
  OcrCapabilitiesWire({this.supportedLanguages, this.models});

  List<String>? supportedLanguages;

  List<OcrModelStateWire>? models;

  List<Object?> _toList() {
    return <Object?>[supportedLanguages, models];
  }

  Object encode() {
    return _toList();
  }

  static OcrCapabilitiesWire decode(Object result) {
    result as List<Object?>;
    return OcrCapabilitiesWire(
      supportedLanguages: (result[0] as List<Object?>?)?.cast<String>(),
      models: (result[1] as List<Object?>?)?.cast<OcrModelStateWire>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! OcrCapabilitiesWire || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(supportedLanguages, other.supportedLanguages) && _deepEquals(models, other.models);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'OcrCapabilitiesWire(supportedLanguages: $supportedLanguages, models: $models)';
  }
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is ScanSourceWire) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is ImageOriginWire) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is ScanStatusWire) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is OcrModelStatusWire) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    } else if (value is ScanOptionsWire) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is GpsDataWire) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is ReceiptExifWire) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is OcrQualityWire) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is ReceiptImageWire) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is ScanResultWire) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else if (value is OcrLineWire) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else if (value is OcrModelStateWire) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else if (value is OcrCapabilitiesWire) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanSourceWire.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ImageOriginWire.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ScanStatusWire.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : OcrModelStatusWire.values[value];
      case 133:
        return ScanOptionsWire.decode(readValue(buffer)!);
      case 134:
        return GpsDataWire.decode(readValue(buffer)!);
      case 135:
        return ReceiptExifWire.decode(readValue(buffer)!);
      case 136:
        return OcrQualityWire.decode(readValue(buffer)!);
      case 137:
        return ReceiptImageWire.decode(readValue(buffer)!);
      case 138:
        return ScanResultWire.decode(readValue(buffer)!);
      case 139:
        return OcrLineWire.decode(readValue(buffer)!);
      case 140:
        return OcrModelStateWire.decode(readValue(buffer)!);
      case 141:
        return OcrCapabilitiesWire.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class ReceiptScannerApi {
  /// Constructor for [ReceiptScannerApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  ReceiptScannerApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
    : pigeonVar_binaryMessenger = binaryMessenger,
      pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<ScanResultWire> scan(ScanOptionsWire options) async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.scan$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[options]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as ScanResultWire;
  }

  /// Reports current OCR capability. Must not download a model or open UI.
  Future<OcrCapabilitiesWire> getOcrCapabilities() async {
    final pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_receipt_scanner.ReceiptScannerApi.getOcrCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
      pigeonVar_replyList,
      pigeonVar_channelName,
      isNullValid: false,
    );
    return pigeonVar_replyValue! as OcrCapabilitiesWire;
  }
}
